### ISSUE TITLE
Add default activity for aborting/failing workflows

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#101]
Migrated from sf.net, feature request 107:

When a workflow gets stuck due to some unexpected circumstances (e.g.: keystore was offline, temporary problems forking openssl, unfortunate solar/lunar alignment, etc.), the most logical action would be to abort the workflow and start the process again. Currently, the only way to resolve a stuck workflow is to just delete it, and this needs to be done in the database.
In the UI, there are buttons for the available actions for a workflow, depending on the current workflow state. It would be helpful to have a default action that is inherited by all states that would allow a workflow to be aborted. Perhaps additional clean-up code could be attached via a hook, that could do things like abort child workflows.
One possible location for this feature would be to put it in the perl data structure that is the result of the XML parsing.

**Comment by oliwel** [comment]
"Force Failure" action is now implemented
