### ISSUE TITLE
Improve certificate request (and possibly CRR) workflows by adding status representation steps

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#104]
Whenever a number of RA Operators are working together on a common request queue it is necessary to coordinate work on incoming requests to avoid duplicated effort or confusing end user communication.

Add additional workflow steps in the CSR and CRR workflows (possibly configurable via policy evaluating conditions that shortcut those states if not needed):

NEW (request not yet processed)
ACCEPTED or PENDING (work in progress by at least one RA Operator)
WAITING_FOR or STALLED (end user response/clarification required)

Add possibility to add comments to the certificate request during processing as background information (not visible for users) for other RA operators.

**Comment by oliwel** [comment]
Implemented with ONHOLD state in CSR, after discussion not considered necessary in CRR
