### ISSUE TITLE
Enrollment workflow, renewal operation: reconsider policy when checking requested DN against existing DN

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#130]
The current code allows to enforce DN policies, such as overwriting parts of the DN with fixed strings (via the Templating feature).
We need to check if this is a problem in the renewal case (e. g. SCEP request signed with existing certificate). If the client is not aware of the "expected" DN (the sanitized one that was set due to the DN policy), it might create a request with a DN that differs from the one expected by the policy.

**Comment by oliwel** [comment]
Fixed "by convention" - a renewal must use the subject of the exisiting certificate. This will breaks if the subject pattern is changed during certificate lifetime, so you should not do this.
