### ISSUE TITLE
Certificate profile should include list of acceptable SAN types

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#141]
Currently the list of accepted Subject Alternative Name types is hardcoded in the GUI (but validated in the backend).

The list of acceptable SAN types for a particular request (distinguish between user create and regofficer edit - possibly give the reg officer a broader choice) should instead be provided by the backend, by default use the RFC 5280 SAN types, but allow limiting the list of acceptable SAN types in a profile.

**Comment by oliwel** [comment]
Done for UI based profiles but needs implementation for SCEP workflow

**Comment by oliwel** [comment]
When render_subject is used (true in the current workflow) the list of SANs is generated from the profile so any existing SANs from the CSR that are not consumed by the template rules are dropped
