### ISSUE TITLE
Provide convenient mechanism for storing credentials (passwords) in encrypted form

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#142]
OpenXPKI needs to connect to various external systems, e. g. for database access, LDAP queries/updates etc. Access to those systems is typically controlled via username/password.

Currently we are already using the Connector to obtain the passwords in plain from the configuration, but plaintext passwords in configs are not desirable.
However, it should be quite easy to use a Connector that queries a data source and obtains the password at runtime, possibly decrypting it on the fly.

Simplify the process by providing the following:
- a command line tool (possibly integrated in openxpkiadm) to encrypt a password (for password changes)
- a Datapool connector that queries the (encrypted) datapool
- a low level "encrypted file" connector (possibly similar to Connector::Builtin::File::Simple) that decrypts the contents of a file on the fly (for cases where Datapool cannot be used, e. g. when bootstrapping the system - Datapool needs the database...)
- documentation and best practices how to configure, set and change passwords using this mechanism
- integrate into the key management infrastructure of OpenXPKI, e. g. using the Data vault mechanism and certificates
- support HSMs

**Comment by oliwel** [comment]
Secret storage and datapool can be used in workflows already
