### ISSUE TITLE
add PKCS12 friendlyname

### ISSUE THREAD

**Issue by rad1us** [openxpki/openxpki#152]
Some software requires a friendlyname set in the PKCS12 in order to import it correctly into an other keystore type.

The friendlyname can either be static "mykey" or could be the certificate subject.

See:
https://www.openssl.org/docs/apps/pkcs12.html

-name friendlyname

```
This specifies the ``friendly name'' for the certificate and private key. This name is typically displayed in list boxes by software importing the file.
```

**Comment by oliwel** [comment]
was fixed with a4677e7a534b7e0835d2f866a5529680ace68124
