### ISSUE TITLE
Crypto backend cleanup: Consider replacing X.509 certificate and request parsing

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#160]
Currently certs and csrs are parsed in our own OpenXPKI.xs module.
Crypt::X509 offers a portable way to parse certificates (using Convert::ASN1) which looks quite well.

Consider migrating to Crypt::X509 and possibly a similar (yet to write, possibly using the same base technology) module for PKCS#10 parsing.

**Comment by oliwel** [comment]
PKCS10 Parsing was (execpt SCE::ExtractCSR) moved to Crypt::PKCS10 already

**Comment by oliwel** [comment]
Consider to also replace CRL parser with ASN1 based module
