### ISSUE TITLE
APT repository GPG key?

### ISSUE THREAD

**Issue by mig5** [openxpki/openxpki#181]
Hi,

I am following your Quick Start guide for Ubuntu Precise here:

https://openxpki.readthedocs.org/en/latest/quickstart.html#debian-ubuntu-development-builds

I have added your APT sources.list entry, but I don't see any instruction on where to fetch your GPG key that you presumably have signed your repo with in order to add it as a trusted repository.

Can you please let me know if it exists and where I could find it? I would rather not install a security-based product from an issuer that I can't authenticate :)

Cheers!

**Comment by gardner** [comment]
Please close this issue. The package installs fine after installing the apt public key. The key is downloaded over http which is less than ideal.

**Comment by oliwel** [comment]
signing key works at least for debian now
