### ISSUE TITLE
Rework transaction handling

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#19]
The current code has no clear and consistent concept of how database transactions should be handled. We need to address and partly rework this.

API functions should not implicitly commit data (which is currently partly done) unless explicitly requested by the caller.
This means that the caller should be able to request "auto-commit" when calling an API function. If this is not the case, the API call should use the same database transaction as the caller.
Typically a transaction will close after completion of a workflow activity, either successful, implying a commit or unsuccessful, which means a transaction rollback. All data manipulated in API functions should also be rolled back.

Caveats:
- log messages and audit trails shall NOT be rolled back, even in case of a failure on application level
- when allowing longer running transactions care must be taken not to introduce deadlocks between server instances both trying to access the same table (this has been observed in the past with accesses to the SECRET table, for example, and was addressed with commit 9b853b63cee07c8497dcb89509c56c1a0e7582c4 - the downside being that now there may be junk left in the database resulting from unwanted commits in case of a later failure in the same logical transaction.

**Comment by oliwel** [comment]
Solved by new sql layer
