### ISSUE TITLE
Display "breadcrumbs" or other navigation help when navigating on non-workflow GUI pages

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#204]
The GUI provides some non-workflow related options, such as certificate search, certificate download, "my tasks" etc.
Sometimes it is difficult to determine the logical context of the currently displayed page.
- print some path information ("breadcrumbs") or other means of identification on the top of the page.
- provide consistent navigation aids on each "non-workflow" page

Example:
- search certificate
- display certificate
- download private key

Result: the user is now on a page from which he or she can only proceed "forward" by entering the private key passphrase and pressing "download".
There is no way go get back to the list of download choices.
In addition the user does not see "where am I now" and "which certificate/key am I downloading".

**Comment by oliwel** [comment]
related to #855
