### ISSUE TITLE
Customizable start page supporting dynamic text macros

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#207]
The user home page (directly displayed after login) should be customizable in the configuration.

Suggestions:
- support role-specific templates (i. e. User gets a different start page than a RA or CA operator)
- allow arbitrary text on the page
- support basic formatting (bold/italic text), tables, enumerations and hyperlinks
- the template should support macros that get expanded to values at run time

Ideas for the macros:
- system generated content, e. g. a macro that renders a list of "my tasks", "my certificates"
- a "search" field (e. g. for workflow id or certifiate serial)
- a "super search" field that accepts a value and tries to find all workflows and certificates that match this number
- a "message of the day" macro that renders the content of an easily modifyable text. Idea: use a datapool namespace for this. datapool key is the name of the referenced MOTD text. Provide a mechanism to set/edit/delete the MOTD for a given key name (only accessible to RA and/or CA operator) -> this allows for basic communication between RA Ops and Users if the MOTD is rendered on the start page of the user

**Comment by oliwel** [comment]
role based start pages and even dynamic ones (via workflow or external script) are already possible
