### ISSUE TITLE
SCEP: enrollment should re-evaluate policy checks on subsequent polling

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#250]
Setup: SCEP enrollment configured to delegate authorization to an external data source.

Client sends SCEP request which passes the authentication step (I believe this issue only applies to authorization, but reconsider this).

SCEP enrollment workflow checks the authorization of the SCEP request.
Authorization source reports that authorization of the request cannot be granted _at this point in time_.

Now, if the client sends subsequent requests the authorization source is not queried again, the cached authorization result is used instead. Even if the authorization would now be granted by the authorization source the request will remain in Authorization Pending.

Possible solution: remodel enrollment workflow to re-evaluate authorization (and possibly authentication) on subsequent requests.

Unclear if this situation could be remedied by invalidating the pending request and starting a new workflow on subsequent SCEP request.

**Comment by oliwel** [comment]
wont do, idea was dropped / can be implemented using watchdog if required
