### ISSUE TITLE
Test for ECDH functions fails due to missing library code

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#315]
The tests for the ECDH functions t/25_crypto/24_xs_ecdh.t fail when doing a make test on a pristine system as the test target does not create the necessary file for the binding. 

Expected: Test target needs to generate the binding code and set env to be able to link it

**Comment by svysh** [comment]
For me term "pristine" is irrelevant. As "make test" fails even after "make install" stage. Thus test target may be not one to be blamed.
