### ISSUE TITLE
Skip key parameter selection if only fixed parameter set is allowed

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#325]
If server side key generation is selected, the user gets a form where all fields are fixed and there is nothing to chose from. Should be skipped silently or presented in a better way

**Comment by oliwel** [comment]
becomes a read only fieldset right now, might be improved with #177

**Comment by maxhq** [comment]
A `<select>` field with only one option and dependant fields is now rendered as static text. With #177 and #897 it also does not lead to any server requests anymore, so there is no visible delay.
