### ISSUE TITLE
 Support for CMP / RFC4210 as NICE backend

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#345]
A generic NICE backend using CMP to create/revoke certificates. 
Can act as gateway to some public CAs (e.g. Quo Vadis).

**Comment by oliwel** [comment]
Most public CAs and other software offer RESTlike APIs in the meantime and there was never a demand for such, dopping request

**Comment by ralienpp** [comment]
On the note for lack of demand, I'd like to say that CMP support could potentially open some doors for an expanded customer base. CMP is the protocol of choice in the 3GPP world, so any telco needs it; and UNISIG SUBSET-137 uses it in rail signalling systems. In the context of post-quantum crypto, CMP would be a way to [get a KEM certificate](https://lamps-wg.github.io/cmp-updates/draft-ietf-lamps-rfc4210bis.html#name-key-encapsulation-mechanism).
