### ISSUE TITLE
menu items not showing translations 

### ISSUE THREAD

**Issue by bsbudhwar** [openxpki/openxpki#355]
![menu not showing properly](https://cloud.githubusercontent.com/assets/18082766/14058747/c53f66d2-f350-11e5-8a9b-5fca28b61aab.jpg)

Please guide me what the issue i installed on turnkey debian linux every thing working only menu and other translations are not working.

![openxpki login raop user](https://cloud.githubusercontent.com/assets/18082766/14058782/c54bb3c8-f351-11e5-8ba3-1a026e90feea.jpg)

**Comment by oliwel** [comment]
I assume that the en_US locale is not installed on the machine - please run "locale -a | grep en_US", the output should be "en_US.utf8". If not, install the english locale.

**Comment by bsbudhwar** [comment]
Hi the language is installed en-US.utf8 see the attachment. Openxpki version 1.6.1

thanks for your reply.
![en_us-utf8 is installed](https://cloud.githubusercontent.com/assets/18082766/14058966/5b618798-f357-11e5-822a-82eb5445e0fd.jpg)

**Comment by oliwel** [comment]
Did you install the language package at all (openxpki-i18n) ?

**Comment by bsbudhwar** [comment]
yes i installed it as per quick guide steps but still same problem. 

![openxpki-i18n](https://cloud.githubusercontent.com/assets/18082766/14058983/d36d1004-f357-11e5-86f1-9aa19ad737f6.jpg)

**Comment by bsbudhwar** [comment]
hi can you tell me were it extracts the language pack usr/share/local ...?

**Comment by oliwel** [comment]
Debian default, so /usr/share/locale/en_US/LC_MESSAGES/openxpki.mo

**Comment by bsbudhwar** [comment]
hi i manualy download the package and unszip the .deb and upload the files via ssh ftp to usr/share/local now its working fine thanks.

Is there any option were i can manage the users like admin users to import root ca files via webui and add or delete users via webui ...?

**Comment by oliwel** [comment]
Hmm, the package looks good and works here without problems, so I wonder this did not work out..

There is no user management included and management  needs mainly to be done on the CLI, check the sample configs in the ca-one/auth/ folder and the quickstart docs.

If you need more help, please use the mailing list https://lists.sourceforge.net/lists/listinfo/openxpki-users
