### ISSUE TITLE
Extra Fields for Extended Validation certs like web server certs

### ISSUE THREAD

**Issue by bsbudhwar** [openxpki/openxpki#357]
Hi is there any other were we can define additional fields like 
street address
locality name
postal code
state name
country etc which is required for extended Validation certificates...?

example 

CN = website.com
O = Multinational, Inc.
L = San Francisco
S = California
C = US
PostalCode = 94107
STREET = 88 Colin P Kelly, Jr Street
SERIALNUMBER = 5157550
1.3.6.1.4.1.311.60.2.1.2 = Delaware
1.3.6.1.4.1.311.60.2.1.3 = US
2.5.4.15 = Private Organization

Birender

**Comment by oliwel** [comment]
Please use the mailinglist to get support https://lists.sourceforge.net/lists/listinfo/openxpki-users
