### ISSUE TITLE
scep error source rendered 

### ISSUE THREAD

**Issue by bsbudhwar** [openxpki/openxpki#359]
![scep error source rendered](https://cloud.githubusercontent.com/assets/18082766/14107072/57785a20-f5d3-11e5-859a-8e3953f707b0.jpg)

hi very thing is automated by installer every thing working fine but scep url rendering source of scep file.

**Comment by oliwel** [comment]
It looks like in recent versions of debian the CGI module is not enable by default - type "a2enmod cgi", restart apache and try again. And please use the mailinglist for non-programming bug related support!
