### ISSUE TITLE
Improve SCEP initial/renewal detection (broken Cisco devices)

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#360]
Cisco IOS routers send scep requests where the request subject does not match the self-signed certificate (unstructured name + CN in request, CN only in certificate). 
They also fail on renewal, as the request subject uses the same format as in the initial case.

Proposed solution: 
- compare public key instead of subject for "self signed"
- relax the "subject matches" checks to parts of the DN/configurable templating for renewal

**Comment by sarefrech** [comment]
Hi, I guess I'm facing this problem with my cisco devices even if I tried unsucessfully to detect how the the request subject is populated by Cisco.
Do you know if a workaround exists for it? Any plan devellop this new feature?
I'm really not sure I can help in the dev itself, sorry.
Thanks,
Régis

**Comment by oliwel** [comment]
We have this on the roadmap but I dont know when it will hit the public. It is possible to workaround this by adjusting the enrollment workflow to the specific environment but this requires some development effort

**Comment by oliwel** [comment]
Solved already in recent workflows
