### ISSUE TITLE
How to issue CRL without auth/wfacl.yaml ?

### ISSUE THREAD

**Issue by StaceZ** [openxpki/openxpki#380]
When i run "openxpkicmd --realm ca-NPK --debug I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE" i get:
---
...
Error:
$VAR1 = {
          'LIST' => [
                      {
                        'LABEL' => 'I18N_OPENXPKI_SERVER_ACL_AUTHORIZE_WORKFLOW_CREATE_PERMISSION_DENIED',
                        'PARAMS' => {
                                      '__ROLE__' => 'System',
                                      '__REALM__' => 'ca-NPK',
                                      '__WF_TYPE__' => 'I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE'
                                    }
                      }
                    ],
          'SERVICE_MSG' => 'ERROR'
        };
---

**Comment by oliwel** [comment]
Can you please using the mailing list for support questions.

I18N_OPENXPKI_WF_TYPE_CRL_ISSUANCE is pre-1.0 config, the crl workflow is now "crl_issuance", so "openxpkicmd --realm ... crl_issuance" shoul work

**Comment by StaceZ** [comment]
Its works! Thanks for response and sorry this bug report ;(
I spent all day on this issue, read all of the available documentation and decided that the file was deleted by mistake; (((
