### ISSUE TITLE
Ubuntu repository is broken

### ISSUE THREAD

**Issue by StaceZ** [openxpki/openxpki#381]
When I use string "deb http://packages.openxpki.org/ubuntu/ trusty/release/" (as written in http://packages.openxpki.org/ubuntu/openxpki.list) I get error:
---
W: Failed to fetch http://packages.openxpki.org/ubuntu/trusty/release/Packages  404  Not Found
---

When I change string to "deb http://packages.openxpki.org/ubuntu/ trusty/release/binary-amd64/" 
system get list of packages, but I get other error:
---
W: GPG error: http://packages.openxpki.org trusty/release/binary-amd64/ Release: Unknown error executing gpgv
---

**Comment by oliwel** [comment]
Thanks for reporting, I fixed the path to the repo. The gpg error is unfortunalty a known issue as we are not able to get package signing to work (see #181)
