### ISSUE TITLE
Web UI wrapper fails to reuse existing socket connections

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#384]
On the backend a new process is spawned for each request. This is a potential performance issue and should be resolved.

**Comment by oliwel** [comment]
Looks like the main look in OXI::Server does not reuse existing childs on incoming connections, so reuse is limited if we can reuse the existing socket binding.
webui.fcgi shares the backend client which "makes this work"
Same needs to be done for scep and rpc wrapper.

Long term solution might be to use another personality of Net::Server

**Comment by oliwel** [comment]
should be solved by the current implementation
