### ISSUE TITLE
I18N_OPENXPKI_TOOLKIT_COMMAND_FAILED;

### ISSUE THREAD

**Issue by itcrowdsource** [openxpki/openxpki#404]
Hello,
I've have created a fresh install of openxpki on Debian Jessie. I've checked the basic configuration several times and all seems to be OK. I'm able to logon to the console where I see a message that I have to create a CRL. If I trigger a CRL issue I'm getting an error message: Unknown error (toolkit command failed) 

Tried to debug the error by starting openxpkictl start --debug 128 

The stderr.log shows many error messages mostly related to openssl. Like I18N_OPENXPKI_TOOLKIT_COMMAND_FAILED

But also errors like these:

2016-08-03 09:26:07.721976 DEBUG:16 PID:1805 OpenXPKI::Server::Workflow::execute_action (line 198): bubbled up error - rethrow
2016-08-03 09:26:07.740090 DEBUG:128 PID:1805 OpenXPKI::Service::__get_error (line 133): $VAR1 = {
2016-08-03 09:26:07.743565 DEBUG:2 PID:1805 OpenXPKI::Service::__get_error (line 135): setup errors array
2016-08-03 09:26:07.743757 DEBUG:2 PID:1805 OpenXPKI::Service::__get_error (line 154): normalize error list
2016-08-03 09:26:07.743951 DEBUG:1 PID:1805 OpenXPKI::Service::__get_error (line 182): return serialized error list

Can anybody help me out with this one? It's driving me nuts. I did the entire installation twice just to be sure I didn't miss anything. 
Initially I only used the Debian packages from the repository and during my second install I've also patched the installation with the most recent files from the Github repository. But all didn't seem to help.
[openxpkilogs.zip](https://github.com/openxpki/openxpki/files/399115/openxpkilogs.zip)

**Comment by oliwel** [comment]
Can you please use the mailinglist for support questions!

From the logs:

            'STATUS' => 'OFFLINE',
            'IDENTIFIER' => 'JE0cN5CI-4hb9ZPdEnPPc04jfyI',
            'ALIAS' => 'ca-one-signer-1', 

This tells me that your CA token ist not availble, you should also see this on the Status page. I guess your private key file is either not in place or has wrong permissions. It must be readable by the openxpki user.

**Comment by itcrowdsource** [comment]
Hi Oliver,

 

My sincere apologies for that, from now I will continue my quest in the group;-)

 

A brief question regarding this issue: Could you point me to the location where the openxpki configuration is stored to retrieve the certificate location/folder? Or briefly explain how the server retrieves these certificates? Does the server use a specific path to e.g. openssl.cnf ?

All permissions are set correctly on the certificates. And all certificates are located in the right folder /etc/openxpki/ssl/ca-one/

 



 

The certificates seem to be imported properly from this same folder:

 



 

With kind regards,

 

Robert Roos

IT Crowdsource

@  <mailto:info@itcrowdsource.com> info@itcrowdsource.com

NL +31-85-8880745

UK +44-20-38682521

**Comment by oliwel** [comment]
Hi Robert,

> My sincere apologies for that, from now I will continue my quest in the
> group;-)

no problem - you are welcome ;)

> A brief question regarding this issue: Could you point me to the
> location where the openxpki configuration is stored to retrieve the
> certificate location/folder? Or briefly explain how the server retrieves
> these certificates? Does the server use a specific path to e.g.
> openssl.cnf ?

There is no openssl.cnf - its generated on the fly in a temporary 
location when we "do the crypto". The issuing *certificates* are never 
read from the disk but are also used from the database. You *must* have 
the private key readable at /etc/openxpki/ssl/ca-one/<aliasname>.pem, 
e.g. ca-one-signer-1.pem for the signer.

It might also be that they keys are readable but the password is 
wrong/not exist - did you protect your keys with a password and did you 
change this in the crypto.yaml ?

Oliver

-- 
Protect your environment -  close windows and adopt a penguin!
