### ISSUE TITLE
Workflow attributes are not transaction safe

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#412]
When setting workflow->attrib the changes are immediatly commited to the database. If using this from within a workflow activity that is rolled back, the attributes do not reflect the intended values. 

As it might be useful to set attribs from "outside" the workflow,an option to commit should be preserved.
Related to #19

**Comment by maxhq** [comment]
This was fixed in 703dc9c782fcc6d4dcd5917775b294171ae89aa4 and merged with PR #537
