### ISSUE TITLE
Add binaries for Ubuntu 16.04 Xenial and for ARM architecture 

### ISSUE THREAD

**Issue by janknieling** [openxpki/openxpki#438]
Hi,

can you please add binaries for Ubuntu 16.04 LTS to your repository and binaries for ARM based systems?

Friendly Regards

**Comment by oliwel** [comment]
Packages for Ubuntu 16.04 are on the way but we wont provide packages for ARM in the near future (unless somebody contributes or funds it).

**Comment by mkauzlar** [comment]
Is there any update for the Ubuntu 16.04 packages?

**Comment by oliwel** [comment]
it looks like they build now but I dont have time to test it - so if you volunteer to give them a try I will upload them to the server

**Comment by mkauzlar** [comment]
sure, I'll give it a try and report back

**Comment by mkauzlar** [comment]
Let me know when you have them uploaded

**Comment by oliwel** [comment]
Freshly build from the new bugfix release http://packages.openxpki.org/ubuntu-xenial/
See the readme for installation hints

**Comment by mkauzlar** [comment]
Ok, got it.
Here are my findings so far:
1. perhaps it's better to put the following in the readme to download the packages:
wget -r -l2 --no-parent --accept "*.deb" http://packages.openxpki.org/ubuntu-xenial/
otherwise it mirrors the whole thing
2. After installation of everything openxpkiadm is missing. Which package provides it?
3. The installation puts the webui in /var/www instead of /var/www/html/ which is the default webroot

**Comment by oliwel** [comment]
We will replace the wget with a real repo once its done but thanks for the hint, I wrote this wtihout checking it back ;)
I just checked the package and all perl files are missing - so this wont work anyway. I did not have thit problem with my test builds yesterday :/
I need to check the build scripts and come back when we figured out whats wrong

**Comment by dalini** [comment]
I'm also looking forward to the 16.04 packages! Just saw the 1.18.1 release for 14.04 LTS - so I go for the above mentioned steps... let's have it a try!

**Comment by dalini** [comment]
Well the ubuntu-xenial is gone?

**Comment by oliwel** [comment]
Package build is broken for Ubuntu 16.04, so we only support 14.04 yet. Also see #482

**Comment by hackdefendr** [comment]
Any progress at all in creating packages for Ubuntu 16.04?  This request has been open for well over a year now. I'm happy to try and fix the build process if there were instructions for installing from source. I need to know what the build dependencies are.

**Comment by oliwel** [comment]
We did not invest on this further and at least the core team wont. There are problems with the build system on ubuntu which differs from debian and we do not have the resources to fix this. 

The primary platform is debian jessie with stock perl for now, we are working on upgrading to strech. If stretch builds work on Ubuntu LTS without any issues, we might bring this back later (likely on Ubuntu 18.04 LTS then)

**Comment by oliwel** [comment]
To build from source you can use the Makefile in core/server/ - last time we investigated the build problem it fails to put the files created into the package dir but installed it directly to the "real" path below the root folder. Also see the contents in package/debian as the cgi wrappers and some other files are not part of the Makefile!
