### ISSUE TITLE
mysql_bind_type_guessing broken

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#44]
The mysql driver sets "mysql_bind_type_guessing => 1"

There was a bug http://bugs.mysql.com/bug.php?id=46786 which should be fixed, but inside OXI the bug is still effective. A standalone script does NOT trigger the bug.

The problem raised when I tried to update a datapool entry with a dp_key of "e4711":
update datapool set datapool_value = ?, encryption_key = ?, last_update = ? where datapool_key = ? and namespace = ? and pki_realm = ?'

**Comment by mbartosch** [comment]
Sample error:

2015/04/16 12:50:43 openxpki.workflow.ERROR:7248 [OpenXPKI::Server::API::Workflow (/usr/lib/perl5/OpenXPKI/Server/API/Workflow.pm:1128); 2050131(RA Operator)@6581] Error executing workflow activity 'csr_approve_csr' on workflow id 3528191 (type certificate_signing_request_v2): I18N_OPENXPKI_SERVER_WORKFLOW_ERROR_ON_EXECUTE; __ERROR__ => I18N_OPENXPKI_SERVER_DBI_DBH_EXECUTE_FAILED; __ERRNO__ => 1292; __ERRVAL__ => Truncated incorrect DOUBLE value: '-wewqZhJ4RdZCyzVtGPx9k-Q3hM'; __QUERY__ => update datapool set datapool_value = ?, encryption_key = ?, notafter = ?, last_update = ? where datapool_key = ? and namespace = ? and pki_realm = ?; __EXCEPTION__ => OpenXPKI::Exception;

**Comment by oliwel** [comment]
Problem reported by mbartosch is a bug in mariadb server (here 5.5.43 enterprise): When a numerical value is compared to a non-numerical value which starts with a digit or sign, a wrong type-cast is made.

To avoid such issues, we decided to turn off mysql_bind_type_guessing by default but add a config option for it.

**Comment by oliwel** [comment]
Finally solved by new DBI layer
