### ISSUE TITLE
Heal whitespace on CSR upload to workaround openssl bug

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#441]
Follow up to discussion in #437 - try to repair whitespace "errors" in uploaded PKCS10

**Comment by tlhackque** [comment]
With `Crypt::PKCS10 1.8` (available once I resolve an elusive test issue), you can easily use it to work-around this OpenSSL bug.
Your code will look like this:
````
my $csr = Crypt::PKCS10->new( $filename, readFile => 1, ignoreNonBase64 => 1  ) or
                                                                die Crypt::PKCS10->error;
my $fixed = $csr->csrRequest(1);
my $signed = qx/openssl ca -batch <<_EOF\n${fixed}_EOF\n/; 
                                  # Hopefully you aren't using openssl's CA :-)
````
That's it.  $fixed is RFC-compliant PEM that OpenSSL (and anyone else) should accept, even with strict parsing.  (Prior to V1.8, csrRequest(1) used MIME's maximum line length, which isn't strictly compliant.)

Note that this also verifies the signature (#437) and parses the entire CSR.  So you can do your policy enforcement, logging, etc from the `$csr` object.

`ignoreNonBase64` will allow (and remove) non-Base64 characters in the PEM block, such as those you get when someone forwards a CSR in an e-mail and it gets quoted with '>'.  It's optional.

Without `ignoreNonBase64`, all the whitespace is removed, but non-Base64 characters will cause the CSR to be rejected.

If you need it, `subjectPublicKey(1)` will also be strictly compliant PEM, so you can feed it to OpenSSL.

I hope this is helpful.
