### ISSUE TITLE
utf8 in the certificates subject 

### ISSUE THREAD

**Issue by sir-xw** [openxpki/openxpki#444]
I did something to allow users put utf8 characters in certificate subject:

```
in Transport/Simple.pm:
- change utf8::downgrade( $data );
+ $data = encode_base64(encode_utf8( $data ));

- utf8::upgrade( $msg );
+ $msg = decode_utf8(decode_base64( $msg ));

in Server/API.pm:
- my $re_sql_string        = qr{ \A [a-zA-Z0-9\@\-_\.\s\%\*\+\=\,\:\ ]* \z }xms;
+ my $re_sql_string        = qr{ \A [\S\@\-_\.\s\%\*\+\=\,\:\ ]* \z }xms;
```

maybe unsafe, but i'm very new to perl.

my problem is, after that I must remove "[% cert_subject %]" from email templates, or the workflow will fail when csr_send_pending_notification.
```
Error executing workflow activity 'csr_submit' on workflow id 14079 (type certificate_signing_request_v2): I18N_OPENXPKI_SERVER_WORKFLOW_ERROR_ON_EXECUTE; __ERROR__ => open body: Invalid argument at /usr/share/perl5/MIME/Entity.pm line 1878.
 at /usr/lib/perl5/OpenXPKI/Server/API/Workflow.pm line 1237.
; __EXCEPTION__ => ; __ACTION__ => csr_send_pending_notification
```

how to deal with this template thing? what happend when  "cert_subject"  go to the email body?

**Comment by oliwel** [comment]
utf8 on the socket should work quite well, so the changes in Transport/Simple shouldnt be necessary. Regarding the SQL string the used regex is very useless - \S is "all non space characters" while "\s" is all spaces, so the regex is just a wildcard on all strings opening the API layer for injection attacks. 

The problem with the mail notification is likely that the module can not handle utf8.

Please consider to use the mailinglists for further discussuions.
