### ISSUE TITLE
Improve CRL / revocation information

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#456]
* number of items on a CRL should be stored in the crl table instead of parsing it from the CRL each time
* each revoked certificate should show the information on what CRL it was added the first time
* extra field for CRL serial number (for importing external CRLs)

**Comment by heginbotham1** [comment]
This is a pretty recent project give them time to add it or edit it yourself this is opensource.

**Comment by mbartosch** [comment]
Related to this:
When displaying a revoked certificate in the GUI the system should show:
- invalidity date/time
- revocation reason

**Comment by oliwel** [comment]
Two things are IMHO worth a discussion

1) Should be allow to have more than one item in the CRR table for each certificate? This would imply that a second CRR can be filed on an already revoke certificate that changes the reason/date. If we allow this we also need to discuss under what cirumstance a new CRR can rule out an old one (and I have no idea if there is any standard/common practise that allows/refuses to update revocation information.

2) I would remove the creator and comment fields from the CRR table as this information is not used in the CRL/OCSP and not covered by any standard. Such extra information can be gathered from the related workflows if required. This leaves revocation time, invalidity time and reason code (and if we support it a day the holdInstructionCode) as columns in the CRR. If we decide to only allow one CRR on each certificate, we might also decide to merged those columns into the certificate table itself. If we keep it in a dedicated table and keep a 1:n relation, I would suggest to add a "crr_key" identifier to unambigously get the correct CRR for each certificate.

**Comment by oliwel** [comment]
Result of discussion:
We allow only one revocation request per certificate and merge this information (revocation time, invalidity time, reason code, holdInstructionCode) into the certificate table. The CRR table will be dropped.
