### ISSUE TITLE
Packaging/Makefile fails to create correct package on Ubuntu 16.04

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#482]
Reusing the existing package script from debian on Ubuntu 16.04 results in packages where anything from /usr/lib/ and /usr/bin is missing. After running the scripts those items are installed on the base system instead going into the package build directory

This prevents delivery of packages and blocks #438

**Comment by dalini** [comment]
I see - can anyone help out here?

**Comment by dalini** [comment]
what needs to be done for the ubuntu 16.04 build? any option to help?

**Comment by heginbotham1** [comment]
Oliwel this is not a bug if im not correct they said this would not work on ubuntu 16.04 right now use 14.04.

**Comment by oliwel** [comment]
@dalini it looks like a problem with the version of Makeutils/Buildtools that comes with Ubuntu 16. 
You need to dig into the build process and "make it work" - have a look at the script vagrant/debian/provision-build.sh which shows the steps we use to make the packages.

**Comment by oliwel** [comment]
@royvandongen if you fix the buildtools we will happily merge and build that upstream. There is a vagrant image already and we prepared a machine for xenial but as said above it does not build. Have a look at the vagrant/debian/ directoy

**Comment by areis422** [comment]
BUMP.

With Ubuntu 14.04 going out of support in April 2019, this should be addressed rather soon.

**Comment by royvandongen** [comment]
Agreed, must confess i did not focus on OpenXPKI anymore because of a shift in work. I'm sorry guys! Keep up the good work!

**Comment by oliwel** [comment]
The community edition will be available for free based on Debian, an upgrade to Debian Buster is under development. Due to several reasons we will not invest more time on community packages for Ubuntu - we are working on a docker container instead.

If you want to have native packages for Ubuntu, there is a commercial offer including packages for Ubuntu 18.04 (it uses a special perl build so this is not easily adoptable to the community edition).

Of course you are free to make the packaging work for Ubuntu - if you share your efforts we are also happy to publish the packages on the project our mirror.
