### ISSUE TITLE
some suse packages not available

### ISSUE THREAD

**Issue by danieldownload** [openxpki/openxpki#496]
Hi there,

can somebody please check the following suse packages? Is there any download mirror?

http://packages.openxpki.org/suse/SLES11/

Those are missing:

myperl-5.22.0-1.x86_64.rpm
myperl-buildtools-5.22.0-1.x86_64.rpm
myperl-dbd-mysql-5.22.0-1.x86_64.rpm
myperl-dbd-oracle-5.22.0-1.x86_64.rpm
myperl-dbi-5.22.0-1.x86_64.rpm
myperl-fcgi-5.22.0-1.x86_64.rpm

cheers,

Daniel

**Comment by oliwel** [comment]
I added the latest packages based on perl 5.24 today and removed those - you should update to openxpki 1.16 and myperl 5.24

**Comment by danieldownload** [comment]
that means I only need to install the following packages and ignore the rest?

myperl-openxpki-core-1.10.0-1.x86_64.rpm
myperl-openxpki-core-deps-1.10.0-1.x86_64.rpm
myperl-openxpki-i18n-1.10.0-1.x86_64.rpm

**Comment by danieldownload** [comment]
The packages for suse just have the old version in it's file name.

The requested URL /suse/SLES11/myperl-fcgi-5.22.0-1.x86_64.rpm was not found on this server.

change file name to ...-2.24... like below

myperl-fcgi-5.24.0-1.x86_64.rpm

then the download works.

cheers Daniel

**Comment by oliwel** [comment]
It looks like you have used a cached version of the former index file, currently http://packages.openxpki.org/suse/SLES11/ just shows a bunch of files.

The latest version is 1.16.6-1 - not 1.10! I will remove the old ones to reduce confusion.
