### ISSUE TITLE
Unable to query tokens of other PKI realm

### ISSUE THREAD

**Issue by maxhq** [openxpki/openxpki#508]
E.g. token operations fail if executed for non-current PKI realm:
```perl
CTX('api')->get_ca_list({ PKI_REALM => 'OTHER' });
```
Methods called:
```perl
OpenXPKI::Server::API::Token->get_ca_list(..)
OpenXPKI::Server::API::Token->is_token_usable(..)
OpenXPKI::Crypto::TokenManager->get_token(..)
OpenXPKI::Crypto::TokenManager->__add_token(..)
OpenXPKI::Config->get_inherit("crypto.token.OTHER.backend")
OpenXPKI::Config->[before '_route_call']
```
The `before '_route_call'` modifier queries the current session PKI realm (`OpenXPKI::Server::Session->get_pki_realm`) and injects it as `realm.$realm` prefix into the config path.

**Possible solution**
Change `TokenManager` to not assume the session PKI realm anymore. Instead directly address the full config path including PKI realm in `OpenXPKI::Crypto::TokenManager->__add_token`. This means `get_token` has to accept a *PKI_REALM* parameter to pass it on to `__add_token`.

**Comment by oliwel** [comment]
From a security perspective tokens from other realms must not be available. Parameter should be removed.
