### ISSUE TITLE
fork inside execute_workflow_actviity causes problems with SIGCHLD

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#517]
If the fork argument is set and the executed child runs actions that make system calls internally (e.g. Proc::SafeExec based CLI calls), the parent process dies with "Signal SIGCHLD received, but no signal handler set"

**Comment by oliwel** [comment]
Seems to be fixed by 37ce3a3aec10896c8c7eb4b9c4652ab892e6ab40
Readding code

**Comment by maxhq** [comment]
Call chains of methods in `OpenXPKI::Server::API::Workflow` that lead to `__execute_workflow_activity` in fork mode:
```perl
resume_workflow({ ... ASYNC => 1})
  -> __wakeup_resume_workflow(?, { ... ASYNC => 1})
      -> __execute_workflow_activity(?, ?, 1)

wakeup_workflow({ ... ASYNC => 1})
  -> __wakeup_resume_workflow(?, { ... ASYNC => 1})
      -> __execute_workflow_activity(?, ?, 1)

execute_workflow_activity(... ASYNC => 1)
  -> __execute_workflow_activity(?, ?, 1)
```

**Comment by maxhq** [comment]
The new test `core/server/t/90_api/31_workflow_async.t` added in de781021d051a57be74818bd2fba93ffb6620b5c seems to confirm that the issue is fixed in the test environment.
Might have been finally solved after `OpenXPKI::Daemonize` was finished in bb8fc3092649cec78041dd755f889c22ab4170d7.

**Comment by oliwel** [comment]
Looks like this finally works now
