### ISSUE TITLE
Throw exception on undefined config value

### ISSUE THREAD

**Issue by maxhq** [openxpki/openxpki#524]
Lots of places in the code use `CTX('config')->get(...)` (_OpenXPKI::Config_) which just returns _undef_ if the specified key does not exist. Some code checks the return value, some doesn't. This can lead to errors very hard to track.

`get()` should throw an exception if the key is unknown and we could introduce a two parameter version where a default value can be supplied:
```perl
CTX('config')->get('non.existing')    # throws exception
CTX('config')->get('non.existing', 5) # returns 5
```

**Comment by oliwel** [comment]
Dont do this! If it matters, check the return value!

CTX('config') is a reference to a "Connector" (or to be more precise to a set of nested connectors).
The connector base class offers the boolean option "die on undef" and it is used in many places that return values can just be undef/empty. Most connectors also offer the "exist" method call to check for the existence of a parameter without getting its value.

See https://github.com/mrscotty/connector/blob/master/lib/Connector.pm to get enlightened on the power of connectors :)
