### ISSUE TITLE
Certificate metadata cannot be deleted when used as scalar

### ISSUE THREAD

**Issue by maxhq** [openxpki/openxpki#527]
Certificate metadata can be updated using the workflow activity class `UpdateCertificateMetadata` (referenced in default workflow *change_metadata*). It reads the metadata key/value pairs from the workflow context.
The intended way to delete a (scalar) metadata key from the database is to set the respective value to *undef* (see [UpdateCertificateMetadata](https://github.com/openxpki/openxpki/blob/develop/core/server/OpenXPKI/Server/Workflow/Activity/Tools/UpdateCertificateMetadata.pm#L109)):
`$wf->context->param('meta_creator' => undef)`
However, the workflow engine does not allow setting a context parameter to *undef*. Thus metadata will not be deleted.

**Workaround**
Treat the metadata as an array, then it can be unset like e.g.:
`$wf->context->param('meta_creator[]' => [])`

**Proposed fix**
Set the parameter as a HashRef:
`$wf->context->param({ 'meta_creator' => undef })`
In this case `Workflow::Base->param()` correctly adds a key with value _undef_.

Especially in `OpenXPKI::Server::Workflow::Activity::Tools::SetContext` we should change
`$context->param($key => $value);`
into
`$context->param( { $key => $value } );`

**Comment by oliwel** [comment]
Fixed with 4fa4d933ed55cd118e960714338b03dd41589e6e
