### ISSUE TITLE
Difference Certificate Serial and Certificate Identifier

### ISSUE THREAD

**Issue by Blackjack92** [openxpki/openxpki#531]
Could you please explain the difference between Certificate Serial and Certificate Identifier?
Which one is unique?

**Comment by oliwel** [comment]
The Certificate Serial is defined by the RFC and part of the certificate. It is generated from a database sequence and therefore unique across a single installation.

The certificate identifier is an OpenXPKI internal value which is created by hashing the certificate content, despite the risk of a hash collision it should be globally unique.

Please use the mailing list for support (https://lists.sourceforge.net/lists/listinfo/openxpki-users)
