### ISSUE TITLE
No web login screen after session timeout

### ISSUE THREAD

**Issue by luzik** [openxpki/openxpki#532]
openxpki.system.FATAL:86 [OpenXPKI::Server (441)#767] Uncaught exception: I18N_OPENXPKI_SERVER_CONTEXT_SETCONTEXT_ALREADY_DEFINED; __NAME__ => service

**Comment by oliwel** [comment]
Please provide more details about the installation and use the mailinglist for support questions 
https://lists.sourceforge.net/lists/listinfo/openxpki-users
