### ISSUE TITLE
Workflow fail after generating password for cert via web

### ISSUE THREAD

**Issue by luzik** [openxpki/openxpki#533]
Error executing workflow activity 'csr_retype_server_password' on workflow id 511 (type certificate_signing_request_v2): I18N_OPENXPKI_SERVER_WORKFLOW_ERROR_ON_EXECUTE; __EXCEPTION__ => OpenXPKI::Exception; __ACTION__ => csr_persist_key_password; __ERROR__ => I18N_OPENXPKI_API_TOKEN_GET_TOKEN_ALIAS_BY_GROUP_NO_RESULT; __GROUP__ => ca-one-vault; __NOTBEFORE__ => 1494571994; __PKI_REALM__ => ca-one; __NOAFTER__ => 1494571994

**Comment by oliwel** [comment]
Please provide more details about the installation and use the mailinglist for support questions 
https://lists.sourceforge.net/lists/listinfo/openxpki-users
