### ISSUE TITLE
openxpkictl start --foreground causes crashes

### ISSUE THREAD

**Issue by DimeOne** [openxpki/openxpki#538]
Hi,

I'm trying to create a docker container for running openxpki using the debian package. Since I have to run the apache and openxpki in the same container I would like to manage these services using a supervisor like supervisord or s6-overlay. To do so I need to run the services in foreground.

While running: 
$ openxpkictl start --foreground 
I am receiving unexpected behaviour. 
When I want to download a certificate file from "Information > CA Certificates > Download" - the first download is successful but the second one fails, which seems due to a crash of the openxpki server process. ( This is only one repro I have been using there are others aswell. )

$ openxpkiadm version
Version (core): 1.17.4

I was able to reproduce this in a debian jessie vm too.

Is there a known way to run the server and watchdog directly through an external supervisor/init system?

My current progress can be found at https://github.com/DimeOne/docker-openxpki Branch: S6 which contains a valid Dockerfile and everything I do in docker-entrypoint.sh - basically quickconfig from http://openxpki.readthedocs.io/en/latest/index.html

**Comment by oliwel** [comment]
The foreground flag is some sort of historic and was intended to be used for debugging, we just did not use it for a long time and it is very likely not doing what you are expecting - this is already "documented" in ticket #343  ;)

The problem you are observing is explained easily - webrequest are handled by a spawned child process which is terminated after the session is closed. The foreground flag prevents the fork but the exit is not prevented, so the daemon simply dies after serving the request.

You can use openxpkictl status or check the existance of the socket file to see if openxpki is running.

Rework of the signal handling and forking is on the roadmap and I will take that into account.

**Comment by DimeOne** [comment]
Thanks for the fast reply,

I'm currently running openxpki start and blocking with apache2ctl -DFOREGROUND - might have problems with zombies but atleast the server keeps running.

Feel free to use anything if you ever plan to create an official image.

https://github.com/DimeOne/docker-openxpki
https://hub.docker.com/r/dime/openxpki/

**Comment by maxhq** [comment]
Hi @DimeOne, although the foreground mode is still not deeply tested, at least for me it works now since commit 3364b7d9c71c674e9bfd702651944f53adae75cb.
Could you please test it again and comment?
Thanks!

**Comment by DimeOne** [comment]
Hi @maxhq sorry for the late response, but I haven't been able to find any installation guide other than installing the .deb packages, so for now I can only wait for the ubuntu image being updated.

Can the scripts that are being used to create the packages be found somewhere? Or is there a documentation to be found?

**Comment by oliwel** [comment]
You can just build the packages by running "make core" in the packages/debian/ directory - note that Ubuntu 16.04 is still NOT building correctly.

Anyway v1.19 is on its way and should be available later this week

**Comment by ravirajshankarl** [comment]
Hi,
 I've gotten the openxpki and sql containers up and running but I can't get EST working. There's no est.fcgi script in /usr/lib/cgi-bin in this image. If I copy the one in the openxpki github to that location but it is throwing 500 error

**Comment by chienaka1211** [comment]
Hi @DimeOne 
![image](https://user-images.githubusercontent.com/67258881/146928784-9a9272cb-befb-43e4-b9aa-7bc2e19094b8.png)
I can't start ,Can you help me? Please
