### ISSUE TITLE
Use consistent way to access pki_realm, user, role

### ISSUE THREAD

**Issue by maxhq** [openxpki/openxpki#544]
Currently there are two different approaches in use throughout the code:
```
CTX('API')->get_pki_realm
CTX('session')->data->pki_realm
```
We should decide for one. I vote for the second as I would expect data like that in the "session".

**Comment by oliwel** [comment]
Basically agreed - but we need to check where the API approach is used and if it makes sense to expose this function to the "outside" api (for the moment, each connection is realm specific so the client should know its realm)

**Comment by oliwel** [comment]
A shortcut to access the realm is required in a lot of places so this will blow up the code and is therefore no longer suggested.
