### ISSUE TITLE
It's Impossible to enabled scep server!!! 

### ISSUE THREAD

**Issue by fabiostrada77** [openxpki/openxpki#560]
Hi,
I installed openxpki. I need to enabled server scep.
Into the documentation of openxpki, It's written this:
"The scep functionality is included as a special service with the core distribution. The scep service needs to be enabled in the global system configuration (system.server.service)."

Where is global system configuration? I don't enabled scep server!!! How can I enable scep server?
Help me!!!!

**Comment by oliwel** [comment]
The scep service IS enable by default but you just need to install the "openca-scep" tools, check the quickstart docs http://openxpki.readthedocs.io/en/latest/quickstart.html#enabling-the-scep-service

Please use the mailinglists for help!

**Comment by fabiostrada77** [comment]
Thanks!!! Now It works!!! 
I tried to make a request scep, using this client:
**https://github.com/certnanny/sscep**

1) I compiled the source code and I generated sscep_dyn  and sscep_static shells (I followed the istructions on readme file). 
2) I make a request, using this commands:
    a)   ./sscep_dyn getca -c tmp/cacert -u http://localhost/scep/scep
    b)   openssl req -new -keyout tmp/scep.key -out tmp/scep.csr -subj '/C=IT/ST=TN/L=Trento/CN=www.mysite.com' -newkey rsa:2048 -nodes
    c)  ./sscep_dyn enroll -u http://localhost/scep/scep -k tmp/scep.key -r tmp/scep.csr -c tmp/cacert-0 -l tmp/scep.crt -t 10 -n 1
3) By "raop" user, I approved the request (on the site http://localhost/openxpki
4) To recovery the certificate, I executed the (2c) command:
./sscep_dyn enroll -u http://localhost/scep/scep -k tmp/scep.key -r tmp/scep.csr -c tmp/cacert-0 -l tmp/scep.crt -t 10 -n 1

The response was:
./sscep_dyn: sending certificate request
./sscep_dyn: valid response from server
./sscep_dyn: reply transaction id: 792C013ECB872C8BA009F4E72EADC60E
./sscep_dyn: pkistatus: SUCCESS
./sscep_dyn: **Subject of our request does not match that of the returned Certificate!**

Is it correct? What means the message "Subject of our request does not match that of the returned Certificate!"? did I make a error?

**Comment by oliwel** [comment]
The above is ok, the OpenXPKI default config just takes the CN from the request and enforces the rest of the DN to be a fixed value

Subscribe to the list https://sourceforge.net/projects/openxpki/lists/openxpki-users and send your questions to openxpki-users@lists.sourceforge.net

**Comment by fabiostrada77** [comment]
Thanks!!!
