### ISSUE TITLE
AND/OR option for metadata search

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#561]
The clonable metadata search fields are internally handled as "AND" search query.
For most setups the majority of metdata items is single valued but the mask accepts to add the same keyword multiple times - some users misinterprete this as "OR"ed search and are disappointed about the empty result.

A pure "OR"ed search might also be insufficient as using different patterns or having multivalued items is possible.

**Comment by maxhq** [comment]
Maybe it should be mentioned in the release notes that there is a backwards incompatible change in the search syntax.
