### ISSUE TITLE
openxpki Scep GETCACERT Command Fail

### ISSUE THREAD

**Issue by josephillips85** [openxpki/openxpki#562]
Hi when im trying to enroll a certificate 
on the step GetCACert i get the following error

 I18N_OPENXPKI_CLIENT_DETACH_FAILED; __MESSAGE_FROM_SERVER__ => $VAR1 = {
[Wed Aug 02 00:20:28.172836 2017] [fcgid:warn] [pid 15801:tid 140092102407936] [client 172.16.50.175:49700] mod_fcgid: stderr: [Wed Aug  2 00:20:28 2017] scep.fcgi:           'LABEL' => 'I18N_OPENXPKI_SERVICE_SCEP_RUN_UNRECOGNIZED_SERVICE_MESSAGE'

to the server is sending http://localhost/scep/tm/?operation=GetCACert and http://localhost/scep/tm/?operation=GetCACert&message=Root%20CA

all of them with the same issue.

any ideas of what i can check?

**Comment by oliwel** [comment]
Check the contents of openxpki.log, did you import and set the SCEP token as given in the quickstart and did you install the openca-scep package? Please consider to use the Mailinglist for support.
