### ISSUE TITLE
Verification Key Downloaded Insecurely

### ISSUE THREAD

**Issue by gardner** [openxpki/openxpki#565]
Going through the docs on installation and noticed that the public key is downloaded via http instead of https. I tried to get the file using https but received an error from the server

Here is the relevant line in the docs. 
https://github.com/openxpki/openxpki/commit/e661664924fa0c087432acd6411c54f7905a243b#diff-dce4048f760a2254db20f3a78d7fcfa1R34

Please consider serving this key securely, or publish it to a key server, or at least include the fingerprint in the docs.

**Comment by gardner** [comment]
or not...

**Comment by oliwel** [comment]
Sorry I dont get your comment, anything that I did wrong or you suggest to improve? 
keyservers dont provide any trust, so there is no benefit for me...

**Comment by gardner** [comment]
Sorry! I totally didn't see the commit. It looks great.
