### ISSUE TITLE
Verify Domains and SCEP not working

### ISSUE THREAD

**Issue by heginbotham1** [openxpki/openxpki#572]
Technically this is an issue because for me to be able to use it as a commercial ca which you said I could how would i Verify domains is there a built in thing or no and I18N_OPENXPKI_CLIENT_SCEP_INVALID_OP also here is the website link 107.175.59.60/scep

**Comment by oliwel** [comment]
I dont understand what you expect to achieve and as Martin said in #571 please consider to use the mailing lists for basic support.

**Comment by heginbotham1** [comment]
Where do I go force mailing list sourceforge
