### ISSUE TITLE
Validation fails on SANs after update, that previously worked - works after config update

### ISSUE THREAD

**Issue by DimeOne** [openxpki/openxpki#587]
Hi Everyone,

I am using Version 1.19.4 and created my configuration using 1.17

I was wondering why I wasn't able to create certificates with SANs anymore, that previously have been workling.

I was trying to create an internal certificate for an non existing public domain - e.g: 
- MyServer.my.lan
- MyServer.qs.ber
- MyServer

All these names exist within our intranet. But when using these values, they fail with: "Value failed allowed expression." 

Is this validation somehow configurable? I was comparing my configuration with the default configuration but could only find minor changes that do not seem linked to this.

My Logfile:
```
2017/11/08 16:57:49 openxpki.application.INFO:91 Execute action csr_edit_san on workflow #12031
2017/11/08 16:57:49 openxpki.application.ERROR:91 Certificate subject validation error
2017/11/08 16:57:49 Workflow.Exception.ERROR:91 validation_error exception thrown from [OpenXPKI::Server::Workflow::Validator::CertSubjectFields: 122; before: OpenXPKI::Server::Workflow::Validator: 154]: I18N_OPENXPKI_UI_VALIDATOR_CERT_SUBJECT_FIELD_HAS_ERRORS
2017/11/08 16:57:49 Workflow.ERROR:91 Caught exception from action: I18N_OPENXPKI_UI_VALIDATOR_CERT_SUBJECT_FIELD_HAS_ERRORS; reset workflow to old state 'ENTER_SAN'
2017/11/08 16:57:49 openxpki.system.ERROR:91 I18N_OPENXPKI_SERVER_WORKFLOW_VALIDATION_FAILED_ON_EXECUTE; __FIELDS__ => ARRAY(0x826bcf8); __ACTION__ => csr_edit_san; __ERROR__ => I18N_OPENXPKI_UI_VALIDATOR_CERT_SUBJECT_FIELD_HAS_ERRORS
2017/11/08 16:57:49 openxpki.workflow.ERROR:91 Error executing workflow activity 'csr_edit_san' on workflow id 12031 (type certificate_signing_request_v2): I18N_OPENXPKI_SERVER_WORKFLOW_VALIDATION_FAILED_ON_EXECUTE; __ACTION__ => csr_edit_san; __ERROR__ => I18N_OPENXPKI_UI_VALIDATOR_CERT_SUBJECT_FIELD_HAS_ERRORS; __FIELDS__ => ARRAY(0x826bcf8)
```

**Comment by DimeOne** [comment]
It seems that I was too soon posting this, after comparing all configuration files, I found some more changes I had to migrate.

**Comment by oliwel** [comment]
Can you post/describe the changes you made? We try hard to make the code updates not break old configs so I am interessted in what caused the problem to see if this is relevant for the default config.
