### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by brocoli-mountain** [openxpki/openxpki#592]
I am going through the quick start guide to test out openxpki (fresh debian installation version 9.2.1), and have found the following issues in the guide so far:

0. aptitude is not installed. I have to use apt instead.
1. `wget https://packages.openxpki.org/debian/Release.key -O - | apt-key add -`
packages.openxpki.org over https redirects to: https://www.ff-indersdorf.de/ so the above command fails. It works over http.
2. `install libopenxpki-perl openxpki-i18n` fails with the following errors:

The following packages have unmet dependencies:
 libopenxpki-perl : Depends: perlapi-5.20.2 but it is not installable
                    Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
                    Depends: libcrypt-openssl-aes-perl but it is not going to be installed
                    Depends: libconnector-perl but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

This is as far as I have got as I've not resolved the above yet, but it's not looking like this is going to be a 'quick start'.

**Comment by oliwel** [comment]
Looks like I missconfigured the Webhost - fixed now.
