### ISSUE TITLE
Fix support for dirName in SAN

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#593]
The dirName type in SAN is not working, the config need to map the DN into a secton which is currently not done: 

```
subjectAltName=dirName:dir_sect

 [dir_sect]
 C=UK
 O=My Organization
 OU=My Unit
 CN=My Name
```

**Comment by oliwel** [comment]
Issuing works now, but it looks like Crypt::PKCS10 chokes on CSRs with dirName extensions 
Parsing request and mapping into the CSR workflow needs to be done.

**Comment by bluelineXY** [comment]
Hi, 
i have extended your implementation which may loose attributes if there DN Elements happen multiple times. 

e.g.: DC=bla,DC=xyz

with your implementation only xyz will come into the certificate. 
See the commit "ed71dff6ce99839c2fb49e7635250616d302b3fb" on my repository. 

Would it make sense to merge this into this repo ?

**Comment by oliwel** [comment]
Contributions are always welcome, please make a pull request against develop with the isolated patch and if possible provide a description with a test case. See also the Contributors notice on the github start page

**Comment by oliwel** [comment]
dirName support is already fixed
