### ISSUE TITLE
Missing sanity check for Crypto Token type vs Crypto Backend API

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#621]
The token API is loaded based on the configuration in system.crypto.tokenapi.TYPE.

However, it is possible to attach a different token type in the crypto token backend configuration.
It is currently not checked if this backend implementation is actually compatible with the tokenapi.

While this is not a problem in most cases, it can become one if there are multiple backend implementations with slightly different API usage.

Suggestion: add a sanity check (possibly in the TokenManager) to verify that the API is compatible with the attached token type.

**Comment by oliwel** [comment]
Tokenapi has been removed, will be reworked finally with new crypto layer
