### ISSUE TITLE
OCSP support

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#636]
OpenXPKI should support OCSP.

**Comment by mbartosch** [comment]
Work in progress. We have chosen to integrate the Cloudflare CFSSL OCSP responder due to extremely low footprint and high performance.
OpenXPKI will precompute the OCSP responses and write them to its database (todo).
The standalone Cloudflare CFSSL OCSP responder is able to directly serve precomputed OCSP responses from the OpenXPKI database schema. This already works with the new OpenXPKI schema in the release/v2 branch.

**Comment by oliwel** [comment]
OCSP support is available as commercial add on
