### ISSUE TITLE
InRelease: The following signatures were invalid: KEYEXPIRED 1527591418

### ISSUE THREAD

**Issue by git-madresc** [openxpki/openxpki#646]
On a jessie installation with a /etc/apt/sources.list.d/openxpki.list deb "http://packages.openxpki.org/debian/ jessie release", apt states an error:

GPG error: http://packages.openxpki.org jessie InRelease: The following signatures were invalid: KEYEXPIRED 1527591418 KEYEXPIRED 1527591418 KEYEXPIRED 1527591418 KEYEXPIRED 1527591418

**Comment by oliwel** [comment]
Updated key is available
https://packages.openxpki.org/v2/debian/Release.key
