### ISSUE TITLE
GetNextCA with SSCEP tool and newer OpenSSL failed

### ISSUE THREAD

**Issue by sebaPran** [openxpki/openxpki#654]
Executing the getnextca command from sscep tool with new OpenSSL version (> 1.0.1t tested) failed with segfault. 

sscep: starting sscep, version 0.6.1
sscep: new transaction
sscep: transaction id: SSCEP transactionId
sscep: hostname: 192.168.0.2
sscep: directory: scep/scep
sscep: port: 80
sscep: SCEP_OPERATION_GETNEXTCA
sscep: server returned status code 200
sscep: MIME header: application/x-x509-next-ca-cert
sscep: reading outer PKCS#7
sscep: PKCS#7 payload size: 2370 bytes
sscep: PKCS#7 contains 855 bytes of signed data
sscep: verifying signature
sscep: signature ok
sscep: The signer certificate verification failed 
Segmentation fault (core dumped)

Debugging the sscep client i find out that the problem is in pkcs7.c in function pkcs7_verify_unwrap in line:

/* Copy enveloped data into PKCS#7 */
s->reply_p7 = d2i_PKCS7_bio(outbio, NULL);

d2i_PKCS7_bio return NULL (which is not handled correct by sscep later on) which indicates an ASN.1 parsing error. I debugged into OpenSSL to find out the exact part of the ASN.1 structure but i was running out of time.

If i use an older version (<= 1.0.1e tested) the parsing works fine and segfault disappears. This article (https://github.com/saltstack/salt/issues/27326) i found indicates that the parsing of ASN.1 structures is more strict in newer OpenSSL versions.

Steps to reproduce:
1. setup openxpki with scep server (Version (core): 1.20.2)
2. setup upcoming root ca certificate
3. build sscep with use of OpenSSL version >= 1.0.1t (static or dynamic does not matter)
4 execute sscep getnextca command

**Comment by oliwel** [comment]
Version 1.x is no longer maintained
