### ISSUE TITLE
Subordinate CA Profile

### ISSUE THREAD

**Issue by mauroparente** [openxpki/openxpki#669]
Hi to all,
i'm trying to create a profile for signing CSR for external subordinate CA. I created a new YAML profile in 
/etc/openxpki/config.d/realm/<realm_name>/profile/ with these configuration:

```
extensions:
    basic_constraints:
        critical: 1
        ca: 1
        path_length: 1

    key_usage:
        critical: 1
        digital_signature: 0
        non_repudiation:   0
        key_encipherment:  0
        data_encipherment: 0
        key_agreement:     0
        key_cert_sign:     1
        crl_sign:          1
        encipher_only:     0
        decipher_only:     0
```

The certificate is generated, but without the "CA:TRUE" constraint. After some debug in code, i think that there is a bug in file "Crypto/Backend/OpenSSL/Config.pm"

```
                if ($pair->[0] eq "CA")
                {
                    if ($pair->[1] eq "true")
                    {
                        $config .= "CA:true,";
                    } else {
                        $config .= "CA:false,";
                    }
                }
```
after changed the condition
`if ($pair->[1] eq "true")`
in
`if ($pair->[1] == 1)`

i've been able to generate the certificate correctly

**Comment by oliwel** [comment]
This duplicates #655 and was fixed with ef4b9b861117478110296bbb68b38ca17e6b556b which is part of the v2.2 release which is available on github, packages will follow within the next days
