### ISSUE TITLE
Unable to 'remove' certificate

### ISSUE THREAD

**Issue by gitsaycat** [openxpki/openxpki#673]
Hi
I am calling openxpkiadm as follows to remove a certificate :
`openxpkiadm certificate remove --realm ca-one --name <cert identifier>`

See the following error: 
`I18N_OPENXPKI_SERVER_CONTEXT_CTX_OBJECT_NOT_DEFINED
   OBJECT: api2`

I am copying and pasting identifier as displayed by openxpki webui

I am running openxpki (v1.20.2) in docker

**Comment by oliwel** [comment]
The 1.x branch is deprecated and will receive only fixed for severe bugs. Please upgrade to the 2.x release. To fix it yourself you need to add "api2" here
https://github.com/openxpki/openxpki/blob/release/v1/core/server/bin/openxpkiadm#L1272

**Comment by syserr0r** [comment]
Still happening on 3.20.0 fwiw
