### ISSUE TITLE
Couldn't find any package whose name or description matched "libcgi-perl" on Debian Jessie 8.11 64-Bit

### ISSUE THREAD

**Issue by asimmehmood201** [openxpki/openxpki#686]
Hi,

I am having issues while installing OpenXPKI 2.0 on Debian Jessie 8.11 64-bit. I am following the steps mentioned in https://openxpki.readthedocs.io/en/latest/quickstart.html

aptitude install libcgi-perl libmodule-load-perl
Couldn't find any package whose name or description matched "libcgi-perl"
Couldn't find any package whose name or description matched "libcgi-perl"
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.

**Comment by oliwel** [comment]
Please use the Mailinglist for support - not the bugtracker -> http://www.openxpki.org/support.html

Those packages are for Ubuntu only - please read the comments on the individual code block and do not just copy&paste - there are sometime alternatives or prereqs.
