### ISSUE TITLE
Plain secrets fail without warning after using an incorrect password once

### ISSUE THREAD

**Issue by simon-wessel** [openxpki/openxpki#693]
After typing in a wrong password for secret groups of the type *plain* the certificates stay offline. This issue remains if the wrong password has been replaced with the correct one. The OpenXPKI service needs to be restarted.

This is somewhat related to #147.

**Comment by oliwel** [comment]
Thanks for reporting this - we know about this problem but did not come up with a good solution so far and as this feature seems to be rarely used there was no priority on this. 
We had a discussion and idea on how to solve this and plan to fix it with the next release.
