### ISSUE TITLE
2.5.3-874af70 problem

### ISSUE THREAD

**Issue by jduemes** [openxpki/openxpki#711]
Hi folks,

yesterday (17-Jul-2019 11:51) was released a new version of OpenXPKI but the systemd unit has a wrong path in it.

```
8,9c8,9
< ExecStart=/opt/myperl/bin/openxpkictl start --nd
< ExecStop=/opt/myperl/bin/openxpkictl stop
---
> ExecStart=/usr/bin/openxpkictl start --nd
> ExecStop=/usr/bin/openxpkictl stop
```

It was only possible to start the service changing the system unit as seen above.

**Comment by oliwel** [comment]
Thank you for reporting this - a fixed package (v2.5.4) is on the way
