### ISSUE TITLE
New CRL not being issued on certificate revocation 

### ISSUE THREAD

**Issue by medinski94** [openxpki/openxpki#729]
Upon revoking a certificate through the UI, the user is presented the watchdog page stating that the reason the certificate_revocation_request_v2 workflow with state CHECK_FOR_REVOCATION was paused was due to "Revocation approved, waiting for next revocation list (CRL) update". The certificate appears to be assigned a status of "revocation pending" instead of "revoked". Only when I explicitly Issue a Certificate Revocation List through the UI the status of the certificate is changed from "revocation pending" to "revoked". 

This behavior also appears to happen on the Openxpki demo site (https://demo.openxpki.org). The only difference is that the workflow does not appear to be paused but is instead successful upon revocation. However, the certificate status will still be "revocation pending" instead of "revoked".

According to the "Issue a Certificate Revocation List" page, "A revocation list is created when there are new revocations or if the current list is near its expiry.". If that is the case, they why are certificate statuses not automatically updated to revoked upon their revocation.

Can anybody confirm if this is a bug or if this is the intended behavior. 

_I am using version 2 of Openxpki inside a Debian Jessie container.
Openxpki is configured using the provided default setup scripts.
During my testing, I was logged in as raop._

Looking through the logs, it appears that a generic exception is thrown for the certificate_revocation_request_v2 workflow.

**openxpki.log**
2019/10/17 21:54:42 ERROR Caught exception from action: [Generic exception]; reset workflow to old state 'CHECK_FOR_REVOCATION' [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]

**catchall.log**

2019/10/17 21:54:41 openxpki.application.INFO Trigger notification message crr_pending_approval [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]
2019/10/17 21:54:42 openxpki.application.INFO Unsigned approval for workflow 3583 by user raop, role RA Operator [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]
2019/10/17 21:54:42 openxpki.audit.approval.INFO operator approval givenHASH(0x8f6d078) [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]
2019/10/17 21:54:42 openxpki.application.INFO start cert revocation for identifier ySkHlAZ4I8qaki_waYdF_XoA8fY, workflow 3583 [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]
2019/10/17 21:54:42 openxpki.application.INFO Action global_check_for_revocation paused (I18N_OPENXPKI_UI_PAUSED_LOCAL_REVOCATION_PENDING), wakeup 2019-10-17T22:24:42 [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]
2019/10/17 21:54:42 Workflow.ERROR Caught exception from action: [Generic exception]; reset workflow to old state 'CHECK_FOR_REVOCATION' [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]

**workflows.log**

2019/10/17 21:54:42 ERROR Caught exception from action: [Generic exception]; reset workflow to old state 'CHECK_FOR_REVOCATION' [pid=8610|sid=XXTT|wftype=certificate_revocation_request_v2|wfid=3583]

**Comment by oliwel** [comment]
Please use the Mailingslists for support- not the Bugtracker
https://sourceforge.net/projects/openxpki/lists/openxpki-users

The Behaviour is intended - the intended use is to setup a cronjob that runs e.g. once a day and triggers the CRL Issuance workflow. If you want to have an CRL instantly created when a certificate is revoked, you need to change the revocation workflow to do so.

The difference between the demo and your install is simply that we have removed the "wait to be revoked" loop in the revocation workflow as this has been shown to be misleading for most users and has no real benefit.
