### ISSUE TITLE
rpc.fcgi: HTTP status should be 4xx if workflow state ends in FAILURE

### ISSUE THREAD

**Issue by mrscotty** [openxpki/openxpki#736]
When a workflow fails, it indicates that there was a fatal problem with the request (e.g. wrong profile, bad csr, automatic or manual rejection, etc.). Currently, the HTTP status code returned by the rpc.fcgi for the FAILURE state is 200, which indicates success. This should be changed to something in the 4xx range to indicate there is a permanent error with the client request that the client must resolve.

To reproduce, submit a request where profile=non-existent. The response should look something like the following:

    Response: &{200 OK 200 HTTP/1.1 1 1 ...
    Response data: {"result":{"proc_state":"finished","state":"FAILURE","id":"376575","data":{"transaction_id":"09c420746d6a496beb79a340fb0e24ae78f0a7ce","error_code":"I18N_OPENXPKI_UI_INVALID_PROFILE"},"pid":18947}}

**Comment by oliwel** [comment]
Failures that are related to the input data "itself" should be caught by a validator so no workflow is started at all (and a 400 is returned).
Logical failures found after the workflow was started will return a 200 to enable the user to see the workflow for debugging information.
