### ISSUE TITLE
rpc.fcgi - resubmitting failed workflow results in multiple workflows with duplicate transaction IDs

### ISSUE THREAD

**Issue by mrscotty** [openxpki/openxpki#737]
To reproduce:

* run certnanny with --profile=bogus

The above creates a workflow with the state FAILURE.

* run certnanny with --profile=tls-server using previous csr

The above creates a second workflow with the same transaction ID. Because the request returns that the workflow is PENDING, certnanny polls a second time and that request fails with a server side error 500 "ambiguous request".

**Comment by oliwel** [comment]
Needs to be fixed in the workflow. Unique pickup definition is possible using the new pickup via datapool feature.
