### ISSUE TITLE
Outdated bungle dependency introduces vulnerability in development process

### ISSUE THREAD

**Issue by l2dy** [openxpki/openxpki#741]
bungle@0.2.0 depends on bower@~1.3.12, which is vulnerable to arbitrary file writes, see https://snyk.io/blog/severe-security-vulnerability-in-bowers-zip-archive-extraction/.

bungle version 0.4.0 removed the `passthrough` pipe, so it's not possibly to use newer versions without configuration change. Please update `bungle.json` to make upgrade possible.

**Comment by oliwel** [comment]
Thank you for pointing this out. We are currently working on a rewrite of the UI component which will no longer use bower/bungle so this bug will become obsolete soon.
