### ISSUE TITLE
Renewing a certificate containing a `directoryName` in its SAN fails

### ISSUE THREAD

**Issue by d-tris** [openxpki/openxpki#747]
When I attempt to do a SCEP renewal of a certificate that has been issued with a `directoryName` specified in its `subjectAltName`, the process fails horribly with an incorrect OpenSSL configuration:

```text
ca: Error on line 78 of config file "/var/tmp/openxpki508uw0R913v/openssl.cnf"                                      
139741499176064:error:0E079065:configuration file routines:def_load_bio:missing equal sign:../crypto/conf/conf_def.c:391:line 78
139741499176064:error:0E079065:configuration file routines:def_load_bio:missing equal sign:../crypto/conf/conf_def.c:391:line 78
```

I'm not sure if there's a way to see these generated configuration files, but the "missing equal sign" makes sense:

The core of the issue seems to be the fact that `Crypt::X509`'s `SubjectAltName` returns the names in a string containing keys and values separated by a comma. Unfortunately, when the name is a `directoryName`, it returns something like `directoryName=HASH(0x7fffec4a9548)`.

So when initial certificate is issued, this nonsensical value [gets parsed](https://github.com/openxpki/openxpki/blob/develop/core/server/OpenXPKI/Crypt/X509.pm#L261) and then [inserted into](https://github.com/openxpki/openxpki/blob/develop/core/server/OpenXPKI/Server/NICE.pm#L183) `certificate_attributes`. Then when the renewal request comes, the value is [loaded from the database](https://github.com/openxpki/openxpki/blob/develop/core/server/OpenXPKI/Server/Workflow/Activity/Tools/PrepareRenewal.pm#L47) and then inserted into the context.

I suspect that this value then gets inserted verbatim into the OpenSSL config, causing OpenSSL to fail.

The issue is partly caused by `Crypt::X509` returning this broken value, but I don't think that's necessarily the problem, given how `directoryName` is a structured value instead of just a plain string. I'd hoped that there is a more structured way of accessing extensions from `Crypt::X509`, but unfortunately I don't see anything like that.

**Comment by oliwel** [comment]
We know that Crypt::X509 fails to parse some attributes and without having checked this I think you are right. If there is already a broken value in the cert_attributes table then the crash in renewal is a follow-up problem, what needs to be fixed is the initial parsing.

To inspect the temp files you need to start OpenXPKI with "openxpkictl --keep-temp-files=yes"

We took over maintenance of the Crypt::X509 module, so if you can/want to fix this please raise a pull request here https://github.com/openxpki/Crypt-X509

**Comment by d-tris** [comment]
>`openxpkictl --keep-temp-files=yes`

Great, I'll try that out.

>We took over maintenance of the Crypt::X509 module, so if you can/want to fix this please raise a pull request here https://github.com/openxpki/Crypt-X509

I was thinking about directly exposing the decoded SAN value without doing any further processing or stringification to it. OpenXPKI could then serialize that and store it without losing any information. `PrepareRenewal` would then have to deserialize and process it accordingly. Does that sound acceptable?

**Comment by oliwel** [comment]
At the moment dirName is implemented as a string which is split at the comma to create the OpenSSL config syntax. It should be easy to let this consume an array of the RDNs which would also "fix" the problem that comma inside the DN are not possible. 
You can find the relevant code in OpenXPKI::Crypto::Backend::OpenSSL::Config starting at line 566
