### ISSUE TITLE
KeyGenerationMode: no selection curve_name

### ISSUE THREAD

**Issue by reawakn** [openxpki/openxpki#757]
If i try Generate key on PKI with Key Algorithm "Elliptic Curve", than i can´t select 
the curves:  example "prime256v1".

The same issue is on online openxpki demo.

Until V.3.4.X it´s okay.

I think on the javascript site is a error. 
If i use until 3.4.X the wwwroot with openxpki server 3.5.6, than i can select the curve.

**Comment by oliwel** [comment]
Oops - the new curve algorithms don't have proper labels set so they can not be displayed. I will fix this with the next release.

**Comment by oliwel** [comment]
The labes have been added but I recognized that switching between RSA and ECC does not work, so you need to chose to either offer RSA or ECC curves for serverside keygen.
