### ISSUE TITLE
Replace external programs (openca-sv and openca-scep) with XS code

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#76]
Partly migrated from sf.net, bug 56:

Remove dependencies of external programs, in particular openca-sv and openca-scep.

---

The openca-sv tool apparently extracts the subject incorrectly from certificates with a subject which has multiple children in an RDN (e.g. CN=a+UID=b). This leads to users with such certificate being unable to login using certificate challenge response authentication, as pkcs7_getchain returns an empty certificate chain (it is 'sorted' by subject/issuer) for those users.

---

Actually, not the openca-sv tool outputs it incorrectly, but the openssl pkcs7 -print_certs command. For UTF8-support, I have added the -text option to the command, but unluckily this does not help with multiple RDNs, which are of the form
DC=org, DC=OpenXPKI, DC=Test Deployment/UID=klink, CN=Alexander Klink
in the output. As '/' is a valid character within an RDN, we can not parse this correctly. We will probably need XS code just to extract a correct RFC2253 DN. OpenSSL sucks here!

**Comment by oliwel** [comment]
openca-scep will be replaced by moving to libscep
