### ISSUE TITLE
How to Import 4 stage CA in OpenXPKI 3.4.0

### ISSUE THREAD

**Issue by scottthomas007** [openxpki/openxpki#760]
Bonjour All,

https://openxpki.readthedocs.io/en/stable/quickstart.html#setup-base-certificates states that it creates a sample 2 stage CA with a Root and an Issuing SubCA. We can also import our already created CA.
What will be the procedure to import a 4 Level CA and the 4th CA is the issuing CA?

Thanks
Scott Thomas

**Comment by oliwel** [comment]
Hi Scott, please use the Mailinglist fir Support - http://www.openxpki.org/support.html - not the Issue Tracker!

OpenXPKI just needs to know the full chain, start with the root and import all additional intermediate certificates the same way. Thats all.
