### ISSUE TITLE
Rework PasswordQuality validator

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#764]
The validator sets the vars for the used module as globals during init which will create "funny results" when the validator is defined more than once with different settings.

Bonus: Have more detailed error codes

Discussion: Dictonary support might be removed or reworked to use some more modern approach as walking through word lists

**Comment by maxhq** [comment]
The password validator now also supports entropy checks etc.
For more information see perldoc of https://github.com/openxpki/openxpki/blob/v3.8.0/core/server/OpenXPKI/Server/Workflow/Validator/PasswordQuality.pm
