### ISSUE TITLE
Missing support for elliptic curve keys

### ISSUE THREAD

**Issue by pertoft** [openxpki/openxpki#766]
Generating a private key using an EC key will break openxpki:
Example:
`openssl req -verbose -config "${OPENSSL_ROOT_CONF}" -extensions v3_datavault_extensions -batch -x509 -newkey ec:<(openssl ecparam -name secp384r1) -days ${DDAYS} -passout file:"${DATAVAULT_KEY_PASSWORD}" -keyout "${DATAVAULT_KEY}" -subj "${DATAVAULT_SUBJECT}" -out "${DATAVAULT_CERTIFICATE}"`

catchall.log:
`2020/08/12 14:50:29 openxpki.system.ERROR OpenSSL error: Error creating PKCS#7 structure
139639072314496:error:08064066:object identifier routines:OBJ_create:oid exists:../crypto/objects/obj_dat.c:709:
139639072314496:error:0D0AE0AB:asn1 encoding routines:oid_module_init:adding object:../crypto/asn1/asn_moid.c:38:
139639072314496:error:0E07606D:configuration file routines:module_run:module initialization error:../crypto/conf/conf_mod.c:177:module=oid_section, value=new_oids, retcode=-1
139639072314496:error:21082096:PKCS7 routines:PKCS7_RECIP_INFO_set:encryption not supported for this key type:../crypto/pkcs7/pk7_lib.c:488:
139639072314496:error:21073078:PKCS7 routines:PKCS7_encrypt:error adding recipient:../crypto/pkcs7/pk7_smime.c:458:
 [pid=22|sid=+pcC]
2020/08/12 14:50:29 openxpki.system.ERROR I18N_OPENXPKI_CRYPTO_CLI_EXECUTE_FAILED; __EXIT_STATUS__ => 768 [pid=22|sid=+pcC]
2020/08/12 14:50:29 openxpki.system.ERROR I18N_OPENXPKI_TOOLKIT_COMMAND_FAILED; __COMMAND__ => OpenXPKI::Crypto::Backend::OpenSSL::Command::pkcs7_encrypt, __ERRVAL__ => I18N_OPENXPKI_CRYPTO_CLI_EXECUTE_FAILED; __EXIT_STATUS__ => 768 [pid=22|sid=+pcC]
2020/08/12 14:50:29 openxpki.system.ERROR Unable to load key from datapool; __KEY__ => ca-signer-1 [pid=22|sid=+pcC]
2020/08/12 14:50:29 openxpki.system.ERROR I18N_OPENXPKI_TOOLKIT_COMMAND_FAILED; __COMMAND__ => OpenXPKI::Crypto::Backend::OpenSSL::Command::pkcs7_sign, __ERRVAL__ => Unable to load key from datapool; __KEY__ => ca-signer-1 [pid=22|sid=+pcC]
2020/08/12 14:50:29 openxpki.system.ERROR OpenSSL error: Error creating PKCS#7 structure
139974711592064:error:08064066:object identifier routines:OBJ_create:oid exists:../crypto/objects/obj_dat.c:709:
139974711592064:error:0D0AE0AB:asn1 encoding routines:oid_module_init:adding object:../crypto/asn1/asn_moid.c:38:
139974711592064:error:0E07606D:configuration file routines:module_run:module initialization error:../crypto/conf/conf_mod.c:177:module=oid_section, value=new_oids, retcode=-1
139974711592064:error:21082096:PKCS7 routines:PKCS7_RECIP_INFO_set:encryption not supported for this key type:../crypto/pkcs7/pk7_lib.c:488:
139974711592064:error:21073078:PKCS7 routines:PKCS7_encrypt:error adding recipient:../crypto/pkcs7/pk7_smime.c:458:
 [pid=22|sid=+pcC]
2020/08/12 14:50:29 openxpki.system.ERROR I18N_OPENXPKI_CRYPTO_CLI_EXECUTE_FAILED; __EXIT_STATUS__ => 768 [pid=22|sid=+pcC]
2020/08/12 14:50:29 openxpki.system.ERROR I18N_OPENXPKI_TOOLKIT_COMMAND_FAILED; __COMMAND__ => OpenXPKI::Crypto::Backend::OpenSSL::Command::pkcs7_encrypt, __ERRVAL__ => I18N_OPENXPKI_CRYPTO_CLI_EXECUTE_FAILED; __EXIT_STATUS__ => 768 [pid=22|sid=+pcC]`

**Comment by oliwel** [comment]
The datavault token must be an RSA token, encryption using ECC is not supported by OpenXPKI
