### ISSUE TITLE
Extend (or clone) MySQL driver to support sequences when runnig MariaDB

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#767]
While native mysql does still not provide sequence support MariaDB comes with sequences so there is no need to use the sequence emulation feature. It should be possible to run OpenXPKI with MariaDBs buildin sequences. 

Will also require to modify the initial schema.

**Comment by maxhq** [comment]
Implemented via 8b592250a5fbf69729edfb172ac8ca3b56ea5577
