### ISSUE TITLE
Certificate templates

### ISSUE THREAD

**Issue by xDFCx** [openxpki/openxpki#771]
Hello.
I'm trying to setup two level enterprise CA with offline root CA and subordinate issuing CA.
I'm facing several difficuties, mostly with certificate templates. There are only 3 templates distributed (and a sample). And no CA/SubCA templates, so I tried to create ony by my own. Unfortunately I couldn't succeed. When trying to issue a certificate (via web interface) using my template I got varios errors. I found the documentation is rather short, and the template sample file, seemed to be self-descriptive, helped me poorly. So I wanted to ask - may be you already have templates for SubCA, AD DC, AD user and so on? So I could just download them. IMHO If templates are not distributed with install package, nor sources, it will be a good idea to create a repo (may be a project on github) with templates, to share.

**Comment by oliwel** [comment]
This is a bugracker - please use the Mailinglist for support https://www.openxpki.org/support.html

OpenXPKI was designed as an End-Entity CA, if you need a Root CA consider to use clca - https://github.com/openxpki/clca
