### ISSUE TITLE
JSCEP client : verification of pkimessage failed due to missing content-type for certificate initial enrollment 

### ISSUE THREAD

**Issue by venkateshdomakonda** [openxpki/openxpki#789]
I am currently investigating the integration of JSCEP client with openxpki for certificates. I am using openxpki-docker steps along with openxpki-sample config for the setup. I managed to start the openxpki CA and issue/download the certificates over GUI which is manual task.

I am trying to automate the certificate enrollment/renewal using the JSCEP client towards openxpki CA.

I followed the JSCEP client steps(with minor change using the same key pair for self signed cert and CSR)  for the enrollment of certificate towards CA.

Looks like the response from openxpki server is not aligned to  RFC 3852 11.1 Check the content-type attribute is correct.

During the initial certificate enrollment transaction  Jscep client performs the PKIMESSAGE signature verification and that is failed due to missing data in  PKCSReq  response.

JSCEP client log:

org.bouncycastle.cms.CMSException: **The content-type attribute type MUST be present whenever signed attributes are present in signed-data**
org.bouncycastle.cms.SignerInformation.doVerify(Unknown Source)
org.bouncycastle.cms.SignerInformation.verify(Unknown Source)
org.jscep.message.PkiMessageDecoder.decode(PkiMessageDecoder.java:115)

From the openxpki logs I could clearly see that certificate is issued but the response for PKCSReq seems to be not aligned to RFC 

OpenXPki Log : 

openxpki.application.INFO LibSCEP PKIOperation; message type: PKCSReq [pid=693|sid=Mqdt]
openxpki.application.INFO **SCEP incoming request**, id cb68fb16a6bc4bf22a97006a7867e357ede6abe1 [pid=693|sid=Mqdt|sceptid=cb68fb16a6bc4bf22a97006a7867e357ede6abe1]
openxpki.application.INFO **SCEP try to start new workflow** for cb68fb16a6bc4bf22a97006a7867e357ede6abe1 [pid=693|sid=Mqdt|sceptid=cb68fb16a6bc4bf22a97006a7867e357ede6abe1]
....
openxpki.application.INFO Trigger notification message **enroll_cert_issued** [pid=693|sid=Mqdt|wftype=certificate_enroll|wfid=3583|sceptid=cb68fb16a6bc4bf22a97006a7867e357ede6abe1]

I browsed through the openxpki PKCSReq  response code and if I understand it correct LIBSCEP library is used to construct the response. Could the response constructed by this method be incorrect.

$certrep = Crypt::LibSCEP::create_certificate_reply($config, $sig_key, $sig_cert, $pkcsreq_or_getcert, $req_cert_or_chain); 
$certrep = Crypt::LibSCEP::create_certificate_reply_wop7($config, $sig_key, $sig_cert, $transid, $senderNonce $enc_cert, $req_cert_or_chain)

I would really appreciate your help in this issue.

Reference : 
Openxpki docker : https://github.com/openxpki/openxpki-docker
JSCEP client : https://github.com/jscep/jscep
SCEP : https://tools.ietf.org/html/rfc8894#section-3
CMS: https://tools.ietf.org/html/rfc3852#section-11.1
LibSCEP : https://metacpan.org/pod/Crypt::LibSCEP

**Comment by oliwel** [comment]
Thank you for this very detailed bug report - we have seen systems working with JSCP in the past but we will have a look into this.
