### ISSUE TITLE
Configuring OpenXPKI for Oracle Database

### ISSUE THREAD

**Issue by kosalalakshitha** [openxpki/openxpki#790]
I am trying to configure openxpki to work with an oracle database.
I tried different combinations on parameters found in database.yaml file. But the server cant seems to connect to the database.
I have already ran the sql script to create the tables. so tables are already there in the DB.
Also I tried using tnsnames.ora file to specify the database. Still no luck.
I could not find any documentation or support forum so I am posting my issue here.
Can anyone help me figure out what configuration should I use?
Thank You

**Comment by mbartosch** [comment]
The issue tracker is for bug reports only, please use the [mailing list](https://sourceforge.net/projects/openxpki/lists/openxpki-users) for this type of questions.
