### ISSUE TITLE
Incorrect English Translation

### ISSUE THREAD

**Issue by LOTRg** [openxpki/openxpki#791]
Translation File for English is incorrectly Showing

>  I18N_OPENXPKI_UI_KEY_CURVE_NAME_SECP521R1 

as 
> Curve sect521r1

While the Deutsche Translation is showing Correctly as 

> Curve secp521r1 

Please fix.

Thank you

**Comment by LOTRg** [comment]
Anyone looking at this please ?

**Comment by oliwel** [comment]
We will fix this with the next release
