### ISSUE TITLE
Random Error with LDAP Auth

### ISSUE THREAD

**Issue by Wolfwood07** [openxpki/openxpki#798]
Hello, we are experiencing an odd situation were randomly our LDAP authentication in Openxpki gives error as if credential were wrong. We can't find what is the actual trigger. Waiting a couple minutes or restarting openxpki resolves the issue but only in temporarily, at any moment it gives error again.
The LDAP is actually a proxy against an Active Directory. We have other apps working against it and we do not notice this kind of problem. We tried changing connection methods from LDAPS to LDAP, avoiding DNS with IP. It is the same.
We don't know what else to try and Log file is certainly not very detailed:

openxpki.auth.WARN I18N_OPENXPKI_SERVER_AUTHENTICATION_LOGIN_FAILED; __error__ => Can't call method "is_error" on an undefined value at /usr/share/perl5/Connector/Builtin/Authentication/LDAP.pm line 298, <DATA> line 755.
 [pid=20341|sid=/1SC]
2021/01/22 06:20:43 openxpki.application.INFO Failed to resume session #B+tbaO1gTXS4ehVKG/EeSA==: unknown ID (maybe expired and purged from backend) [pid=20341|]
2021/01/22 06:20:43 openxpki.system.ERROR I18N_OPENXPKI_SERVICE_DEFAULT_HANDLE_CONTINUE_SESSION_SESSION_CONTINUE_FAILED; __ID__ => B+tbaO1gTXS4ehVKG/EeSA== [pid=20341|]
2021/01/22 06:20:43 openxpki.system.WARN Invalid message COMMAND received in state WAITING_FOR_AUTHENTICATION_STACK [pid=20341|sid=ilOH]
2021/01/22 06:20:47 openxpki.auth.WARN I18N_OPENXPKI_SERVER_AUTHENTICATION_LOGIN_FAILED; __error__ => Can't call method "is_error" on an undefined value at /usr/share/perl5/Connector/Builtin/Authentication/LDAP.pm line 274, <DATA> line 755.
 [pid=20341|sid=rbMk]

My guess would be that Openxpki(or the ldap perl module) establishes a session to the ldap server and from time to time it looses it. But even if that is the issue without more details we don't know why or what to change to make this more stable.

**Comment by oliwel** [comment]
I will accept this as a bug report for the very unfriendly error (Net::LDAP->bind seems to return undef which is not mentioned clearly to be possible in the docs and not checked by our code). 
For support questions please use the mailinglist.

**Comment by oliwel** [comment]
Auth Errors should be more visible, linking #617

**Comment by oliwel** [comment]
Should be improved with new Auth Layer and logging enhancements in v3.12
