### ISSUE TITLE
Import database schema error

### ISSUE THREAD

**Issue by ShojinSpear** [openxpki/openxpki#799]
Hi all, 

I´m try to install the system in a new Debian machine, but when I try to import the MariaDB Schema  I receive the following error:
zcat /usr/share/doc/libopenxpki-perl/examples/schema-mariadb.sql.gz  | >  mysql -u root --password --database  openxpki

ERROR 1068 (42000) at line 199: Multiple primary key defined

**Comment by oliwel** [comment]
Works here, you likely already initialised the DB already. 
Please use the Mailinglist for support.
