### ISSUE TITLE
RAOP cant approve CSR vid Digital Signature using ECC Certs

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#80]
Migrated from sf.net, bug 71

I had installed and configured OpenXPKI with ECC using CURVE_NAME prime239v1 and applied all the suggested patches at the forum...Now the CA certificate is 239-bit ECC based. Then i tried to generate an ECC certificates for "CA Operator" , "RA Operator" , "End User" and "Web Server". The certificate was successfully generated but of RSA-2048.... When i try to approve CSR's with Digital Signature using certificate of RAOP...then this type of error occurs with Javascript "E-Mail users are not supported".....and then "Invalid Signature" is displayed at web page.
I have already installed CA certificate in my Firefox Web Browser(Version 3.5.5). Also i have checked the 3 options while installing this certificate in my browser.

**Comment by oliwel** [comment]
Brower signature is no longer supported due to missing APIs
