### ISSUE TITLE
PKCS10 how to read 2.5.4.97 - organizationIdentifier

### ISSUE THREAD

**Issue by flybyray** [openxpki/openxpki#800]
Is it possible to read the organizationIdentifier from a CSR?

**Comment by flybyray** [comment]
Is this the problem with that TODO?
https://github.com/openxpki/openxpki/commit/02cf643b564f16199592a29f00445354ec74eeb4#diff-b4e5561df922178697f7f036814603cc303291276b989eb387189055ef6c13eaR59

**Comment by mbartosch** [comment]
Please use the OpenXPKI Users Mailing List for general support questions. This issue tracker is to be used only for bugs and feature requests.

We have not yet encountered a customer request which requires processing of attributes required by the ETSI standards. Our typical approach is to do that when the need arises.
