### ISSUE TITLE
SCEP AES encryption support

### ISSUE THREAD

**Issue by MichalMMac** [openxpki/openxpki#802]
Current documentation for SCEP server `encryption_algorithm` option states:

> Encrpytion to use, supported values are \<DES> and \<3DES>.

[rfc8894(https://tools.ietf.org/html/rfc8894) says:

> For historical reasons, implementations MAY support communications of
   binary data via HTTP GET (Section 4.1), and the triple DES-CBC and
   SHA-1 algorithms to secure pkiMessages (Section 3.2).
   Implementations MUST NOT support the obsolete and/or insecure single
   DES and MD5 algorithms used in earlier versions of this
   specification, since the unsecured nature of GetCACaps means that an
   in-path attacker can trivially roll back the encryption used to these
   insecure algorithms; see Section 7.5.

What about about AES? Would it be possible to support it?

**Comment by oliwel** [comment]
This is just a documentation bug - supported values are _des | 3des | des3 | aes128 | aes192 | aes256 | blowfish | cast_
