### ISSUE TITLE
logrotate service fails because of default OpenXPKI setup

### ISSUE THREAD

**Issue by MichalMMac** [openxpki/openxpki#813]
This is a replacement for issue #812. When deploying OpenXPKI into production (Debian 10), monitoring system informed me about failed `logrorate.service`. Reason for that being logrotate unable to rotate openxpki log files. There are several problems.

# Testing environment

Debian 10.9 Buster.
OpenXPKI 3.12 CE (latest version)
Default logrorate config in `/etc/logrotate.conf`:
```
weekly
rotate 4
create
include /etc/logrotate.d
```

OpenXPKI default logrotate configuration in `/etc/logrotate.d/openxpki`:
```
/var/log/openxpki/catchall.log 
/var/log/openxpki/openxpki.log
/var/log/openxpki/connector.log
/var/log/openxpki/workflow.log
/var/log/openxpki/stderr.log {
    daily
    copytruncate
    compress
    rotate 5 
    su openxpki root
    notifempty
    dateext
}

/var/log/openxpki/rpc.log
/var/log/openxpki/scep.log
/var/log/openxpki/soap.log
/var/log/openxpki/webui.log
/var/log/openxpki/est.log {
    daily
    copytruncate
    compress
    rotate 5 
    su www-data root
    notifempty
    dateext
}
```

# Reproduction

1. Install and setup the OpenXPKI following the QuickStart guide.
2. Package install creates empty directory `/var/log/openxpki/` with permissions `drwsrwxr-x 2 openxpki openxpki`. Note the setuid bit. Any reason for it?
3. When `openxpki.service` is started, daemon crates following log files:
```
-rw-rw---- 1 root root  264 May 26 10:00 audit.log
-rw-rw---- 1 root root 1242 May 26 10:00 catchall.log
-rw-rw---- 1 root root  137 May 26 10:00 deprecated.log
-rw-rw---- 1 root root  684 May 26 10:00 openxpki.log
-rw-rw---- 1 root root  398 May 26 10:00 stderr.log
-rw-rw---- 1 root root    0 May 26 10:00 workflows.log
```
4. Now try to use `logrotate -f /etc/logrotate.conf`. Result:
```
error: stat of /var/log/openxpki/connector.log failed: No such file or directory
error: stat of /var/log/openxpki/workflow.log failed: No such file or directory
error: error setting owner of /var/log/openxpki/catchall.log-20210526 to uid 0 and gid 0: Operation not permitted
error: error setting owner of /var/log/openxpki/openxpki.log-20210526 to uid 0 and gid 0: Operation not permitted
error: error setting owner of /var/log/openxpki/stderr.log-20210526 to uid 0 and gid 0: Operation not permitted
error: stat of /var/log/openxpki/rpc.log failed: No such file or directory
error: stat of /var/log/openxpki/scep.log failed: No such file or directory
error: stat of /var/log/openxpki/soap.log failed: No such file or directory
error: stat of /var/log/openxpki/webui.log failed: No such file or directory
error: stat of /var/log/openxpki/est.log failed: No such file or directory
```
And the directory:
```
-rw-rw---- 1 root     root  264 May 26 10:00 audit.log
-rw-rw---- 1 root     root 1444 May 26 10:20 catchall.log
-rw------- 1 openxpki root    0 May 26 10:22 catchall.log-20210526
-rw-rw---- 1 root     root  137 May 26 10:00 deprecated.log
-rw-rw---- 1 root     root  779 May 26 10:00 openxpki.log
-rw------- 1 openxpki root    0 May 26 10:22 openxpki.log-20210526
-rw-rw---- 1 root     root  398 May 26 10:00 stderr.log
-rw------- 1 openxpki root    0 May 26 10:22 stderr.log-20210526
-rw-rw---- 1 root     root    0 May 26 10:00 workflows.log
```

## Missing log files problem

Since I haven't do anything with the OpenXPKI yet there are missing logs. However some of theses log files would never be created because f.e. I don't plan to use SOAP at all. 

This could be solved by adding the `missingok` option to `/etc/logrotate.d/openxpki`.

## Workflow log type problem

Note the error: `stat of /var/log/openxpki/workflow.log failed: No such file or directory`. This is a clear typo in openxpki logrotate configuration since there is no workflow.log but workflow**s**.log

Easy fix. Just change the `/var/log/openxpki/workflow.log` to `/var/log/openxpki/workflows.log` in `/etc/logrotate.d/openxpki`.

## Daemon permission problem

Now to the permissions problem. Rotation of the log files in question was never completed creating empty files such as stderr.log-20210526. If I change the owner of these log files from `root` to `openxpki` rotation works. 

```
-rw-rw---- 1 openxpki root 264 May 26 10:00 audit.log
-rw-rw---- 1 openxpki root   0 May 26 10:23 catchall.log
-rw-rw---- 1 openxpki root 470 May 26 10:20 catchall.log-20210526.gz
-rw-rw---- 1 openxpki root 137 May 26 10:00 deprecated.log
-rw-rw---- 1 openxpki root   0 May 26 10:23 openxpki.log
-rw-rw---- 1 openxpki root 232 May 26 10:00 openxpki.log-20210526.gz
-rw-rw---- 1 openxpki root   0 May 26 10:23 stderr.log
-rw-rw---- 1 openxpki root 283 May 26 10:00 stderr.log-20210526.gz
-rw-rw---- 1 openxpki root   0 May 26 10:00 workflows.log
```

Problem is rotating the root:root files with the `su openxpki root` logrotate option.

## Web wrapper permission problem

To create the log file for testing I accessed the web interface so `webui.log` log file is created:
```
-rw-r--r-- 1 www-data www-data 675 May 26 10:29 webui.log
```
Apache running as `www-data` is able to create this file because package install makes the `www-data` member of `openxpki` group.

After running the `logrotate -f /etc/logrotate.conf` I get following error:

```error: error creating output file /var/log/openxpki/webui.log-20210526: Permission denied```

No rotated file was created.

My current workaround for that is to change logrote configuration from `su www-data root` to `su root www-data`.

# Conclusion

Unless I am missing something obvious openxpki logrotate config needs rethinking (permission problems). I might be able to help with a PR  but first I need to know what are the desired permissions for live log files, rotated logfiles and the openxpki log directory.

**Comment by oliwel** [comment]
Log handling is somewhat PITA - for our customer installs we switched over to Journald logging which is unfortunately not an option on Debian as the underlying libs are too old to work wit the Log4perl Journald driver.

The easiest option would be to add the recreate option to the log definitions and use delayedcompress - I will add a patch to the next release for this.

**Comment by MichalMMac** [comment]
> Log handling is somewhat PITA - for our customer installs we switched over to Journald logging which is unfortunately not an option on Debian as the underlying libs are too old to work wit the Log4perl Journald driver.

I guess Debian 11 is going to resolve this problem, right?

**Comment by oliwel** [comment]
I did not have a look at it, so possibly yes but there are no plans to go for Debian 11 yet - it depends a bit on how much they have changed and the efforts needed to get it running.
