### ISSUE TITLE
How to add selfsigned gost certificate as a root.crt?

### ISSUE THREAD

**Issue by achechet** [openxpki/openxpki#815]
Openxpki on DEbian 10.10 with gost-engine/
I have issue self signed root certificate (ghost based) and try to import it with openxpkiadm.
But it stop with errors....
Can't locate object method "new" via package "Crypt::x509" .....

What is going wrong?

**Comment by oliwel** [comment]
OpenXPKI supports RSA, ECC and DSA - GOST is no longer supported by the upstream packages.
Please use the Mailinglist for support questions http://www.openxpki.org/support.html
