### ISSUE TITLE
How to start OpenXPKI with alternative locale?

### ISSUE THREAD

**Issue by achechet** [openxpki/openxpki#818]
I have restart system with Russian locale but never see any changes at web interface
How to start OpenXPKI with alternative locale?

Please never address me to mailing list to support - I cannot understood how to ask questions there

**Comment by mbartosch** [comment]
As a general rule we do not answer general support requests on the issue tracker. This issue tracker is for bugs and feature requests only.

You have the following two options:
- subscribe to the Users Mailing List which is as easy as filling out the form at https://sourceforge.net/projects/openxpki/lists/openxpki-usersv 
- subscribe to a support contract with White Rabbit Security
