### ISSUE TITLE
How to start OpenXPKI with alternative locale?

### ISSUE THREAD

**Issue by achechet** [openxpki/openxpki#819]
I have restart system with Russian locale but never see any changes at web interface
How to start OpenXPKI with alternative locale?

Please never address me to mailing list to support - I cannot understood how to ask questions there
@mbartosch
Member
mbartosch commented 21 minutes ago •

As a general rule we do not answer general support requests on the issue tracker. This issue tracker is for bugs and feature requests only.

You have the following two options:

    subscribe to the Users Mailing List which is as easy as filling out the form at https://sourceforge.net/projects/openxpki/lists/openxpki-users
    subscribe to a support contract with White Rabbit Security

I have already subscribe there to Mailing list
I have never found there support contract with White Rabbit Security? 
Please be patient and explain

**Comment by mbartosch** [comment]
To post to the mailing list, simply send an email to the list address openxpki-users@lists.sourceforge.net using the sender email address you registered.

If you are interested in commercial support please contact office@whiterabbitsecurity.com
