### ISSUE TITLE
LDAP filter issue with 389-ds

### ISSUE THREAD

**Issue by jessejohnson-bnet** [openxpki/openxpki#828]
Hello. I'm setting up openxpki with our redhat 389-ds server but having a problem with the filter.
I'm using last week's docker installed versions.  3.14 I believe. 

This works
    filter: "(uid=first.last)"

Neither of thes work from openxpki but do work fine from ldapsearch commandline.
    filter: "(uid=*)"
    filter: "(memberOf=CN=pkiadmin,OU=groups,OU=redacted,OU=redacted,DC=redacted,DC=redacted)"

[root@ldap001 ~]# ldapsearch  -D "<binddn>" -W  -H ldaps://<ldapserver>  "(memberOf=CN=pkiadmin,OU=groups,OU=redacted,OU=redacted,DC=redacted,DC=redacted)"

\# extended LDIF
\#
\# LDAPv3
\# base <dc=redacted,dc=redacted> (default) with scope subtree
\# filter: (memberOf=CN=pkiadmin,OU=groups,OU=redacted,OU=redacted,DC=redacted,DC=redacted)
\# requesting: ALL
\#

\# jesse.johnson, redacted, People, redacted, redacted, redacted
dn: uid=jesse.johnson,ou=redacted,ou=People,ou=redacted,ou=redacted,dc=redacted,dc=redacted
memberOf: cn=pkiadmin,ou=groups,ou=redacted,ou=redacted,dc=redacted,dc=redacted
memberOf: cn=pkiuser,ou=groups,ou=redacted,ou=redacted,dc=redacted,dc=redacted
cn: Jesse Johnson
uid: jesse.johnson
sn: Johnson
givenName: Jesse

\# search result
search: 1
result: 0 Success

\# numResponses: 2
\# numEntries: 1

**Comment by oliwel** [comment]
Please use the Mailingslist for support, this is for confirmed bugs or explicitly defined feature requests only
