### ISSUE TITLE
Allowed to create realm with <.> period in realm name, but it doesn't work correctly. 

### ISSUE THREAD

**Issue by jessejohnson-bnet** [openxpki/openxpki#829]
I tried to create a realm word1.word2 and it caused all sorts of weird login/role/certimport issues. It wouldn't show up correctly in the realm drop down list, had cert import issues (they wouldn't show up in the GUI)

When I recreated the realm word1word2 it all worked correctly.

**Comment by oliwel** [comment]
Please use the Mailingsliste for support, this is for confirmed bugs or explicitly defined feature requests only
