### ISSUE TITLE
Run with NGINX instead of Apache

### ISSUE THREAD

**Issue by WeebHiroyuki** [openxpki/openxpki#833]
Hey,
Is it possible to use NGINX as my reverse proxy instead of the Apache Web Server? In `apt install libopenxpki-perl openxpki-cgi-session-driver openxpki-i18n`, the first package seems to install many dependencies along with `apache2`. I'd strongly prefer NGINX over Apache.

**Comment by oliwel** [comment]
http://www.openxpki.org/support.html
