### ISSUE TITLE
san_guid

### ISSUE THREAD

**Issue by atol71** [openxpki/openxpki#834]
Hi,

How would you define san type san_guid. So far i've tried:
in <profile_name>.yaml
ui:
    san:
        - san_guid
...

<profile_name>.yaml template: section / san_guid.yaml file in profile/template
simple id,label,description,type,with definition

without a luck. 

In examples it states that san.ui should handle this automatically. I have extension 1.3.6.1.4.1.311.25.1 (MS) in extended_key_usage. In sample.yaml there is san: san_guid.

Any help would be appreciated.

S.H.

**Comment by oliwel** [comment]
http://www.openxpki.org/support.html
