### ISSUE TITLE
I18N_OPENXPKI_UI_APPLICATION_ERROR

### ISSUE THREAD

**Issue by ma3goul** [openxpki/openxpki#838]
Hi All ,

I installed the openxpki binaries on debian 10 , I ran the sampleconfig.sh script to create and configure the Ca automatically just for test purpose .
when I try to access the web ui I get this :
![image](https://user-images.githubusercontent.com/65537018/158182395-fe8f9365-b705-4c2a-bfb8-358ed9b12beb.png)

Any help please ?
Thank you

**Comment by oliwel** [comment]
www.openxpki.org/support.html
