### ISSUE TITLE
Implement indirect CRLs (needs OpenSSL support)

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#84]
Migrated from sf.net. Feature request 1

The configuration is already prepared for dedicated CRL
issuance CAs (using the <issue_for> tag), but the code
still needs to be implemented in the CRL workflow.

---

Implemented in r1244 - the syntax has changed a bit though. The CA issuer is now defined in the <crl_publication> section of the CA for which the CRL is created - that makes the config and code much shorter compared to listing all CAs for which a certain CA issues CRLs ...

---

OK, so the fix in r1244 was too easy - that only allows one to issue CRLs with a different CA. For indirect CRLs, the Certificate Issuer CRL entry extension is needed though so that one can actually know who issued the revoked certificate. This seems not to be supported by OpenSSL at the moment, unluckily.

**Comment by oliwel** [comment]
was never requested by a customer - dropping
