### ISSUE TITLE
GUI input fields do not process some special characters properly

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#845]
Some (all)? text fields do not accept special characters, such as German umlauts.

Reproduce:
- raise request
- put request on hold
- enter some text in the text area (justification for on-hold)
- use non-ASCII chars, e. g. German Umlauts

If submitted, the GUI displays a red error banner indicating invalid characters in UTF8 input data.

**Comment by maxhq** [comment]
This was fixed in v3.20.
