### ISSUE TITLE
Support for CRL hold OIDs and invalidity time extensions

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#85]
Migrated from sf.net. Feature request 20:

The X.509 standard allows for an invalidity time CRL entry extension, that allows to specifiy when a certificate became invalid. Unluckily, this extension can only be specified using some reason codes in OpenSSL. Same goes for certificateHold which has an additional OID that specifies what to do on hold. This can only be specified when using a pseudo reason code for it, but not using certificateHold - how is one supposed to do that?
It would be good if we could figure out if there is a way that these extensions can be written from OpenSSL.

**Comment by oliwel** [comment]
invalidity time is supported, HOLD was never requested by any customer - dropping
