### ISSUE TITLE
Trying to get OpenAPI spec from /rpc endpoint results in error

### ISSUE THREAD

**Issue by Luk164** [openxpki/openxpki#862]
Hi, I am having trouble getting `curl -F "method=openapi-spec" http://<My URL:port>/rpc`. When I try it I get a 404 error. Also when I use https port I get a generic loading screen and then error.

I am running on docker using latest containers.

In the meanwhile could somebody please provide the OpenAPI spec file?

Thanks

Edit: Sorry for the big edit I got confused a little and though something from EJBCA applied here as well.

**Comment by mbartosch** [comment]
Please use the [OpenXPKI users mailing list](https://www.openxpki.org/support.html) for support questions on the OpenSource edition of OpenXPKI.
