### ISSUE TITLE
Missing libdbd-mysql-perl dependency in the docs?

### ISSUE THREAD

**Issue by gam04** [openxpki/openxpki#882]
For version 3.26.0, it seems it's necessary to install both `libdbd-mysql-perl ` and `libdbd-mariadb-perl`, even though the docs say
only  `libdbd-mariadb-perl ` it's necessary.

If you only install `libdbd-mariadb-perl` the service fails when trying to connect to DB. The same if you only install `libdbd-mariadb-perl`

**Comment by oliwel** [comment]
Thats not right, it depends on which Database Driver you choose - with MariaDB you need `libdbd-mysql-perl` and with MariaDB2 `libdbd-mysql-perl`  should be sufficient
