### ISSUE TITLE
MariaDB2 driver error when attempting to connect to higher version of external MariaDB Instance.

### ISSUE THREAD

**Issue by jogalt** [openxpki/openxpki#894]
I've successfully configured a connection to an external Galera cluster with the following settings:
```
type: MariaDB2
    name: openxpki_dev
    host: db-mariadb.domain.name
    port: 3306
    user: openxpki_dev
    passwd: p@$$word
```
 but had to make a change in the following file:
/usr/share/perl5/OpenXPKI/Server/Database/Driver/MariaDB2.pm

On line 58, it's set to die 
```
unless ($major >= 10 and $minor >= 3);
```
I was receiving this error after configuring the server to connect to the external database.
```
Exception during server initialization: Database not connected; __error__ => MariaDB server too old: 11.1.2 - OpenXPKI 'MariaDB' driver requires version 10.3, please use 'MySQL' instead. at /usr/share/perl5/OpenXPKI/Server/Database/Driver/MariaDB2.pm line 58.
 (Database not connected; __error__ => MariaDB2 server too old: 11.1.2 - OpenXPKI 'MariaDB2' driver requires version 10.3, please use 'MySQL' instead. at /usr/share/perl5/OpenXPKI/Server/Database/Driver/MariaDB2.pm line 57.
```

As you can see from the logs my Galera cluster is running 11.1.2. I ended up changing the comparators to:
```
unless ($major >= 1 and $minor >= 1);
```
After this, the server started up and everything is working as expected. I'll let it run a few days and see if any issues or errors show up.

**Comment by maxhq** [comment]
Hi @jogalt and thanks for reporting. This version number comparison was not really useful – and it was done by me :)
I have now fixed it internally and it will soon be published to Github.

**Comment by jogalt** [comment]
Glad to help!
