### ISSUE TITLE
The requested URL has no service assigned.

### ISSUE THREAD

**Issue by PIKACHUIM** [openxpki/openxpki#906]
https://********:****/openxpki/cgi-bin/webui.fcgi?page=bootstrap%21structure&baseurl=%2Fopenxpki%2F&_=1704788191083
https://********:****/openxpki/cgi-bin/webui.fcgi?page=welcome&_=1704788191042
```
{
    "status": {
        "level": "error",
        "message": "The requested URL has no service assigned."
    }
}
```
Thank you!

**Comment by oliwel** [comment]
Please use the Mailinglist for support, not the issue tracker: https://www.openxpki.org/#resources

**Comment by PIKACHUIM** [comment]
Thanks!
