### ISSUE TITLE
certificate request validation like ACME for manual requests (approval process/ customer request validation/ ACME like challange for manual request)

### ISSUE THREAD

**Issue by neginsadeghi** [openxpki/openxpki#908]
Hi there, Thanks for all your hard work.

I'm thinking about how can I authorize the client that is requesting the certificate against the SAN or domains that he is trying to get certificate for. I mean consider a public CA, they would verify contact of ssl certificate, they would check http challenge, DNS record challenge and stuff like that. how can I do this in openxpki ? 

I want it only for web ssl certificates, the ones that has valid domain names ( routing available on internet so no worries about http/dns or any other challanges )

**Comment by mbartosch** [comment]
For general support questions please use the [OpenXPKI Users Mailing List](https://lists.sourceforge.net/lists/listinfo/openxpki-users) hosted by sourceforge.net. Please do not create issues on the Github Issue Tracker for support questions.
