### ISSUE TITLE
When I use sscep to send enroll request to openxpki, the error returned is I18N_OPENXPKI_UI_INVALID_PROFILE

### ISSUE THREAD

**Issue by SNKCG** [openxpki/openxpki#922]
I set the policy in openxpki to the simplest one to allow anonymous requests, and also generated the correct csr request, but after testing it many times, it still reported the error I18N_OPENXPKI_UI_INVALID_PROFILE

**Comment by mbartosch** [comment]
For general support questions please use the [OpenXPKI Users Mailing List](https://lists.sourceforge.net/lists/listinfo/openxpki-users) hosted by sourceforge.net. Please do not create issues on the Github Issue Tracker for support questions.
