### ISSUE TITLE
Post quantum support roadmap

### ISSUE THREAD

**Issue by ralienpp** [openxpki/openxpki#925]
The product page description says the CA aims to provide support for post-quantum algorithms, and the image next to the text hints that lattice-based algorithms would be there. However, I browsed through the online demo, searched the documentation and source code and found nothing PQ-related.

Is this functionality already available for testing? Do you have an approximate timeline for this?

**Comment by mbartosch** [comment]
Please use the [OpenXPKI Mailing Lists](https://sourceforge.net/p/openxpki/mailman/openxpki-users/) for general questions.
