### ISSUE TITLE
Private key usage counter and auditing

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#96]
Migrated from sf.net, feature request 97

For each private key used by OpenXPKI maintain a usage counter that is increased on each explicit use of this key. (Consider digitally signing this counter.)
If an independent system could keep track of actual private key usage count, OpenXPKI could compare the expected usage count with the one reported by the independent system.
Should the reported numbers differ, this would mean the private key was (ab)used outside of OpenXPKI. The application could notice this and raise an audit monitoring event.
While mostly useless for keys stored in software, this would be a great feature when used with an HSM that supports a tamper-proof private key usage counter.

Note to self: consider nCipher Secure Execution Engine for implementation of this feature.

**Comment by oliwel** [comment]
no demand - dropping
